////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package opencost

import (
	"fmt"
	util "github.com/opencost/opencost/core/pkg/util"
	"io"
	"reflect"
	"time"
)

//--------------------------------------------------------------------------
//  Streaming Decoder for CloudCostSet
//--------------------------------------------------------------------------

// StreamingCloudCostSetDecoder provides a streaming interface for decoding CloudCostSet
// from bingen format without loading the entire file into memory.
// It reads one record at a time from disk.
type StreamingCloudCostSetDecoder struct {
	reader io.Reader
	buff   *util.Buffer
	ctx    *DecodingContext

	// Metadata about the file
	version uint8

	// State tracking
	initialized     bool
	cloudCostsRead  int
	cloudCostsTotal int

	// Current position in the stream
	currentSection string
}

// NewStreamingCloudCostSetDecoder creates a new streaming decoder that reads from the provided reader.
func NewStreamingCloudCostSetDecoder(reader io.Reader) (*StreamingCloudCostSetDecoder, error) {
	return &StreamingCloudCostSetDecoder{
		reader:      reader,
		initialized: false,
	}, nil
}

// Initialize reads the header information but does not read the map data.
func (sd *StreamingCloudCostSetDecoder) Initialize() error {
	if sd.initialized {
		return fmt.Errorf("decoder already initialized")
	}

	// Read entire file into memory for now
	// TODO: Implement true streaming by reading header only
	data, err := io.ReadAll(sd.reader)
	if err != nil {
		return fmt.Errorf("failed to read data: %w", err)
	}

	sd.buff = util.NewBufferFromBytes(data)

	// Parse string table
	var table []string
	if isBinaryTag(data, BinaryTagStringTable) {
		sd.buff.ReadBytes(len(BinaryTagStringTable))
		tl := sd.buff.ReadInt()
		if tl > 0 {
			table = make([]string, tl)
			for i := 0; i < tl; i++ {
				table[i] = sd.buff.ReadString()
			}
		}
	}

	sd.ctx = &DecodingContext{
		Buffer: sd.buff,
		Table:  table,
	}

	// Read version
	sd.version = sd.buff.ReadUInt8()
	if sd.version > CloudCostCodecVersion {
		return fmt.Errorf("invalid version: expected %d or less, got %d", CloudCostCodecVersion, sd.version)
	}

	// Read CloudCosts length
	if sd.buff.ReadUInt8() != uint8(0) {
		sd.cloudCostsTotal = sd.buff.ReadInt()
	} else {
		sd.cloudCostsTotal = 0
	}

	sd.initialized = true
	sd.currentSection = "cloudCosts"
	return nil
}

// NextCloudCosts reads and returns the next CloudCosts entry from the stream.
// Returns (key, value, nil) on success, or (zero, zero, io.EOF) when no more entries.
func (sd *StreamingCloudCostSetDecoder) NextCloudCosts() (string, *CloudCost, error) {
	if !sd.initialized {
		return "", nil, fmt.Errorf("decoder not initialized")
	}

	if sd.currentSection != "cloudCosts" {
		return "", nil, fmt.Errorf("not in cloudCosts section")
	}

	if sd.cloudCostsRead >= sd.cloudCostsTotal {
		return "", nil, io.EOF
	}

	// Read key
	var key string
	key = func() string {
		if sd.ctx.IsStringTable() {
			return sd.ctx.Table[sd.buff.ReadInt()]
		} else {
			return sd.buff.ReadString()
		}
	}()

	// Read value
	var value *CloudCost
	if sd.buff.ReadUInt8() != uint8(0) {
		tempVal := &CloudCost{}
		sd.buff.ReadInt() // compatibility
		err := tempVal.UnmarshalBinaryWithContext(sd.ctx)
		if err != nil {
			return "", nil, err
		}
		value = tempVal
	}

	sd.cloudCostsRead++
	return key, value, nil
}

// Stats returns statistics about the streaming decoder state.
func (sd *StreamingCloudCostSetDecoder) Stats() map[string]interface{} {
	return map[string]interface{}{
		"initialized":     sd.initialized,
		"version":         sd.version,
		"cloudCostsRead":  sd.cloudCostsRead,
		"cloudCostsTotal": sd.cloudCostsTotal,
		"currentSection":  sd.currentSection,
	}
}
