////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package opencost

import (
	"fmt"
	util "github.com/opencost/opencost/core/pkg/util"
	"io"
	"reflect"
	"time"
)

//--------------------------------------------------------------------------
//  Streaming Decoder for AssetSet
//--------------------------------------------------------------------------

// StreamingAssetSetDecoder provides a streaming interface for decoding AssetSet
// from bingen format without loading the entire file into memory.
// It reads one record at a time from disk.
type StreamingAssetSetDecoder struct {
	reader io.Reader
	buff   *util.Buffer
	ctx    *DecodingContext

	// Metadata about the file
	version uint8

	// State tracking
	initialized bool
	assetsRead  int
	assetsTotal int

	// Current position in the stream
	currentSection string
}

// NewStreamingAssetSetDecoder creates a new streaming decoder that reads from the provided reader.
func NewStreamingAssetSetDecoder(reader io.Reader) (*StreamingAssetSetDecoder, error) {
	return &StreamingAssetSetDecoder{
		reader:      reader,
		initialized: false,
	}, nil
}

// Initialize reads the header information but does not read the map data.
func (sd *StreamingAssetSetDecoder) Initialize() error {
	if sd.initialized {
		return fmt.Errorf("decoder already initialized")
	}

	// Read entire file into memory for now
	// TODO: Implement true streaming by reading header only
	data, err := io.ReadAll(sd.reader)
	if err != nil {
		return fmt.Errorf("failed to read data: %w", err)
	}

	sd.buff = util.NewBufferFromBytes(data)

	// Parse string table
	var table []string
	if isBinaryTag(data, BinaryTagStringTable) {
		sd.buff.ReadBytes(len(BinaryTagStringTable))
		tl := sd.buff.ReadInt()
		if tl > 0 {
			table = make([]string, tl)
			for i := 0; i < tl; i++ {
				table[i] = sd.buff.ReadString()
			}
		}
	}

	sd.ctx = &DecodingContext{
		Buffer: sd.buff,
		Table:  table,
	}

	// Read version
	sd.version = sd.buff.ReadUInt8()
	if sd.version > AssetsCodecVersion {
		return fmt.Errorf("invalid version: expected %d or less, got %d", AssetsCodecVersion, sd.version)
	}

	// Read Assets length
	if sd.buff.ReadUInt8() != uint8(0) {
		sd.assetsTotal = sd.buff.ReadInt()
	} else {
		sd.assetsTotal = 0
	}

	sd.initialized = true
	sd.currentSection = "assets"
	return nil
}

// NextAssets reads and returns the next Assets entry from the stream.
// Returns (key, value, nil) on success, or (zero, zero, io.EOF) when no more entries.
func (sd *StreamingAssetSetDecoder) NextAssets() (string, Asset, error) {
	if !sd.initialized {
		return "", nil, fmt.Errorf("decoder not initialized")
	}

	if sd.currentSection != "assets" {
		return "", nil, fmt.Errorf("not in assets section")
	}

	if sd.assetsRead >= sd.assetsTotal {
		return "", nil, io.EOF
	}

	// Read key
	var key string
	key = func() string {
		if sd.ctx.IsStringTable() {
			return sd.ctx.Table[sd.buff.ReadInt()]
		} else {
			return sd.buff.ReadString()
		}
	}()

	// Read value
	var value Asset
	if sd.buff.ReadUInt8() != uint8(0) {
		typeName := sd.buff.ReadString()
		_, resolvedName, _ := resolveType(typeName)
		if _, ok := typeMap[resolvedName]; !ok {
			return "", nil, fmt.Errorf("unknown type: %s", resolvedName)
		}
		concrete, ok := reflect.New(typeMap[resolvedName]).Interface().(BinDecoder)
		if !ok {
			return "", nil, fmt.Errorf("type %s does not implement BinDecoder", resolvedName)
		}
		sd.buff.ReadInt() // compatibility
		err := concrete.UnmarshalBinaryWithContext(sd.ctx)
		if err != nil {
			return "", nil, err
		}
		value = concrete.(Asset)
	}

	sd.assetsRead++
	return key, value, nil
}

// Stats returns statistics about the streaming decoder state.
func (sd *StreamingAssetSetDecoder) Stats() map[string]interface{} {
	return map[string]interface{}{
		"initialized":    sd.initialized,
		"version":        sd.version,
		"assetsRead":     sd.assetsRead,
		"assetsTotal":    sd.assetsTotal,
		"currentSection": sd.currentSection,
	}
}
