syntax = "proto3";

package kubemodel;
option go_package = "github.com/opencost/opencost/core/pkg/model/pb/kubemodel";

// Unit represents the unit of measurement for resources
enum Unit {
  UNIT_M = 0; // Unit of CPU ("millicore")
  UNIT_MI = 1; // Unit of RAM ("mebibyte")
  UNIT_GPU = 2; // Unit of GPU ("GPU")
  UNIT_GB = 3; // Unit of storage size ("gigabyte")
  UNIT_B = 4; // Unit of network transfer ("byte")
  UNIT_M_HR = 5; // Unit of CPU-hours ("millicore-hour")
  UNIT_MI_HR = 6; // Unit of RAM-hours ("mebibyte-hour")
  UNIT_GB_HR = 7; // Unit of storage size-hours ("gigabyte-hour")
  UNIT_HR = 8; // Unit of time ("hour")
}

// ResourceQuantity represents a quantity of a specific resource
message ResourceQuantity {
  Unit unit = 1;
  double quantity = 2;
}

// ResourcePrice represents the price per unit of a specific resource
message ResourcePrice {
  Unit unit = 1;
  double pricePerUnit = 2;
}