version: 2
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/core" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/modules/collector-source" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/modules/prometheus-source" # Location of package manifests
    schedule:
      interval: "weekly"

  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
