apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost-uid
  namespace: opencost
  labels:
    app: opencost-uid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencost-uid
  template:
    metadata:
      labels:
        app: opencost-uid
    spec:
      serviceAccountName: opencost
      containers:
        - name: opencost
          image: opencost:local-uid
          imagePullPolicy: Never
          ports:
            - containerPort: 9003
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "http://prometheus-server.prometheus-system.svc"
            - name: CLUSTER_ID
              value: "cluster-one"
          resources:
            requests:
              cpu: "10m"
              memory: "55M"
            limits:
              cpu: "999m"
              memory: "1G"
---
apiVersion: v1
kind: Service
metadata:
  name: opencost-uid
  namespace: opencost
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9003"
spec:
  selector:
    app: opencost-uid
  type: ClusterIP
  ports:
    - name: opencost
      port: 9003
      targetPort: 9003
