sonar.projectKey=opencost_opencost
sonar.sources=pkg,core/pkg,modules/prometheus-source/pkg,modules/collector-source/pkg
sonar.go.coverage.reportPaths=coverage.out,coverage/coverage.out,core/coverage.out,modules/prometheus-source/coverage.out,modules/collector-source/coverage.out
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/*_test.go