package collector

func NewOpenCostMetricCollector() MetricsCollector {
	memCollector := NewInMemoryMetricsCollector()

	// Register all the metrics
	memCollector.Register(NewPVPricePerGiBHourMetricCollector())
	memCollector.Register(NewPVUsedAverageMetricCollector())
	memCollector.Register(NewPVUsedMaxMetricCollector())
	memCollector.Register(NewPVCInfoMetricCollector())
	memCollector.Register(NewPVActiveMinutesMetricCollector())
	memCollector.Register(NewLocalStorageCostMetricCollector())
	memCollector.Register(NewLocalStorageUsedCostMetricCollector())
	memCollector.Register(NewLocalStorageUsedAverageMetricCollector())
	memCollector.Register(NewLocalStorageUsedMaxMetricCollector())
	memCollector.Register(NewLocalStorageBytesMetricCollector())
	memCollector.Register(NewLocalStorageActiveMinutesMetricCollector())
	memCollector.Register(NewNodeCPUCoresCapacityMetricCollector())
	memCollector.Register(NewNodeCPUCoresAllocatableMetricCollector())
	memCollector.Register(NewNodeRAMBytesCapacityMetricCollector())
	memCollector.Register(NewNodeRAMBytesAllocatableMetricCollector())
	memCollector.Register(NewNodeGPUCountMetricCollector())
	memCollector.Register(NewNodeLabelsMetricCollector())
	memCollector.Register(NewNodeActiveMinutesMetricCollector())
	memCollector.Register(NewNodeCPUModeTotalMetricCollector())
	memCollector.Register(NewNodeRAMSystemUsageAverageMetricCollector())
	memCollector.Register(NewNodeRAMUserUsageAverageMetricCollector())
	memCollector.Register(NewLBPricePerHourMetricCollector())
	memCollector.Register(NewLBActiveMinutesMetricCollector())
	memCollector.Register(NewClusterManagementDurationMetricCollector())
	memCollector.Register(NewClusterManagementPricePerHourMetricCollector())
	memCollector.Register(NewPodActiveMinutesMetricCollector())
	memCollector.Register(NewRAMBytesAllocatedMetricCollector())
	memCollector.Register(NewRAMRequestsMetricCollector())
	memCollector.Register(NewRAMUsageAverageMetricCollector())
	memCollector.Register(NewRAMUsageMaxMetricCollector())
	memCollector.Register(NewCPUCoresAllocatedMetricCollector())
	memCollector.Register(NewCPURequestsMetricCollector())
	memCollector.Register(NewCPUUsageAverageMetricCollector())
	memCollector.Register(NewCPUUsageMaxMetricCollector())
	memCollector.Register(NewGPUsRequestedMetricCollector())
	memCollector.Register(NewGPUsUsageAverageMetricCollector())
	memCollector.Register(NewGPUsUsageMaxMetricCollector())
	memCollector.Register(NewGPUsAllocatedMetricCollector())
	memCollector.Register(NewIsGPUSharedMetricCollector())
	memCollector.Register(NewGPUInfoMetricCollector())
	memCollector.Register(NewNodeCPUPricePerHourMetricCollector())
	memCollector.Register(NewNodeRAMPricePerGiBHourMetricCollector())
	memCollector.Register(NewNodeGPUPricePerHourMetricCollector())
	memCollector.Register(NewNodeIsSpotMetricCollector())
	memCollector.Register(NewPodPVCAllocationMetricCollector())
	memCollector.Register(NewPVCBytesRequestedMetricCollector())
	memCollector.Register(NewPVBytesMetricCollector())
	memCollector.Register(NewPVCostPerGiBHourMetricCollector())
	memCollector.Register(NewPVInfoMetricCollector())
	memCollector.Register(NewNetZoneGiBMetricCollector())
	memCollector.Register(NewNetZonePricePerGiBMetricCollector())
	memCollector.Register(NewNetRegionGiBMetricCollector())
	memCollector.Register(NewNetRegionPricePerGiBMetricCollector())
	memCollector.Register(NewNetInternetGiBMetricCollector())
	memCollector.Register(NewNetInternetPricePerGiBMetricCollector())
	memCollector.Register(NewNetReceiveBytesMetricCollector())
	memCollector.Register(NewNetTransferBytesMetricCollector())
	memCollector.Register(NewNamespaceLabelsMetricCollector())
	memCollector.Register(NewNamespaceAnnotationsMetricCollector())
	memCollector.Register(NewPodLabelsMetricCollector())
	memCollector.Register(NewPodAnnotationsMetricCollector())
	memCollector.Register(NewServiceLabelsMetricCollector())
	memCollector.Register(NewDeploymentLabelsMetricCollector())
	memCollector.Register(NewStatefulSetLabelsMetricCollector())
	memCollector.Register(NewDaemonSetLabelsMetricCollector())
	memCollector.Register(NewJobLabelsMetricCollector())
	memCollector.Register(NewPodsWithReplicaSetOwnerMetricCollector())
	memCollector.Register(NewReplicaSetsWithoutOwnersMetricCollector())
	memCollector.Register(NewReplicaSetsWithRolloutMetricCollector())

	return memCollector
}

// There are a couple ways we can make "Reporting" of the metrics a bit cleaner:
// -- we can write thin API friendly wrappers that can be used to funnel value updates into
//    collector.Update(...) calls [similar to prom]. This is purely convenience and there isn't
//    really an architecture bearing weight on this decisions. Whatever is easier to use.
