// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: kubemodel/cluster.proto

package kubemodel

import (
	pb "github.com/opencost/opencost/core/pkg/model/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provider represents the cloud provider or infrastructure type
type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED  Provider = 0
	Provider_PROVIDER_AWS          Provider = 1
	Provider_PROVIDER_GCP          Provider = 2
	Provider_PROVIDER_AZURE        Provider = 3
	Provider_PROVIDER_ON_PREMISES  Provider = 4
	Provider_PROVIDER_ALIBABA      Provider = 5
	Provider_PROVIDER_DIGITALOCEAN Provider = 6
	Provider_PROVIDER_ORACLE       Provider = 7
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_AWS",
		2: "PROVIDER_GCP",
		3: "PROVIDER_AZURE",
		4: "PROVIDER_ON_PREMISES",
		5: "PROVIDER_ALIBABA",
		6: "PROVIDER_DIGITALOCEAN",
		7: "PROVIDER_ORACLE",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED":  0,
		"PROVIDER_AWS":          1,
		"PROVIDER_GCP":          2,
		"PROVIDER_AZURE":        3,
		"PROVIDER_ON_PREMISES":  4,
		"PROVIDER_ALIBABA":      5,
		"PROVIDER_DIGITALOCEAN": 6,
		"PROVIDER_ORACLE":       7,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_kubemodel_cluster_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_kubemodel_cluster_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_kubemodel_cluster_proto_rawDescGZIP(), []int{0}
}

// Cluster represents the top-level Kubernetes cluster
type Cluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	// User-configured cluster identifier, defaults to kube-system namespace UID
	// The kube-system namespace UID is unique per cluster and stable across its lifetime
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Properties
	Provider Provider `protobuf:"varint,2,opt,name=provider,proto3,enum=kubemodel.Provider" json:"provider,omitempty"`
	Account  string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Name     string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Centralized window definition for entire cluster
	// All resources inherit this window unless they specify their own duration
	Window *pb.Window `protobuf:"bytes,5,opt,name=window,proto3" json:"window,omitempty"`
	// Resources within the cluster
	Containers             []*Container             `protobuf:"bytes,6,rep,name=containers,proto3" json:"containers,omitempty"`
	Controllers            []*Controller            `protobuf:"bytes,7,rep,name=controllers,proto3" json:"controllers,omitempty"`
	GpuDevices             []*GPUDevice             `protobuf:"bytes,9,rep,name=gpu_devices,json=gpuDevices,proto3" json:"gpu_devices,omitempty"`
	GpuUsage               []*GPUUsage              `protobuf:"bytes,10,rep,name=gpu_usage,json=gpuUsage,proto3" json:"gpu_usage,omitempty"`
	Namespaces             []*Namespace             `protobuf:"bytes,11,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Services               []*Service               `protobuf:"bytes,12,rep,name=services,proto3" json:"services,omitempty"`
	Nodes                  []*Node                  `protobuf:"bytes,13,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Pods                   []*Pod                   `protobuf:"bytes,14,rep,name=pods,proto3" json:"pods,omitempty"`
	Volumes                []*Volume                `protobuf:"bytes,15,rep,name=volumes,proto3" json:"volumes,omitempty"`
	PersistentVolumeClaims []*PersistentVolumeClaim `protobuf:"bytes,16,rep,name=persistent_volume_claims,json=persistentVolumeClaims,proto3" json:"persistent_volume_claims,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_kubemodel_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_kubemodel_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_kubemodel_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Cluster) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *Cluster) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetWindow() *pb.Window {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *Cluster) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *Cluster) GetControllers() []*Controller {
	if x != nil {
		return x.Controllers
	}
	return nil
}

func (x *Cluster) GetGpuDevices() []*GPUDevice {
	if x != nil {
		return x.GpuDevices
	}
	return nil
}

func (x *Cluster) GetGpuUsage() []*GPUUsage {
	if x != nil {
		return x.GpuUsage
	}
	return nil
}

func (x *Cluster) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *Cluster) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Cluster) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Cluster) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *Cluster) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Cluster) GetPersistentVolumeClaims() []*PersistentVolumeClaim {
	if x != nil {
		return x.PersistentVolumeClaims
	}
	return nil
}

var File_kubemodel_cluster_proto protoreflect.FileDescriptor

const file_kubemodel_cluster_proto_rawDesc = "" +
	"\n" +
	"\x17kubemodel/cluster.proto\x12\tkubemodel\x1a\x12model/window.proto\x1a\x19kubemodel/container.proto\x1a\x1akubemodel/controller.proto\x1a\x13kubemodel/gpu.proto\x1a\x19kubemodel/namespace.proto\x1a\x17kubemodel/network.proto\x1a\x14kubemodel/node.proto\x1a\x13kubemodel/pod.proto\x1a\x17kubemodel/storage.proto\"\xb1\x05\n" +
	"\aCluster\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12/\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x13.kubemodel.ProviderR\bprovider\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x06window\x18\x05 \x01(\v2\r.model.WindowR\x06window\x124\n" +
	"\n" +
	"containers\x18\x06 \x03(\v2\x14.kubemodel.ContainerR\n" +
	"containers\x127\n" +
	"\vcontrollers\x18\a \x03(\v2\x15.kubemodel.ControllerR\vcontrollers\x125\n" +
	"\vgpu_devices\x18\t \x03(\v2\x14.kubemodel.GPUDeviceR\n" +
	"gpuDevices\x120\n" +
	"\tgpu_usage\x18\n" +
	" \x03(\v2\x13.kubemodel.GPUUsageR\bgpuUsage\x124\n" +
	"\n" +
	"namespaces\x18\v \x03(\v2\x14.kubemodel.NamespaceR\n" +
	"namespaces\x12.\n" +
	"\bservices\x18\f \x03(\v2\x12.kubemodel.ServiceR\bservices\x12%\n" +
	"\x05nodes\x18\r \x03(\v2\x0f.kubemodel.NodeR\x05nodes\x12\"\n" +
	"\x04pods\x18\x0e \x03(\v2\x0e.kubemodel.PodR\x04pods\x12+\n" +
	"\avolumes\x18\x0f \x03(\v2\x11.kubemodel.VolumeR\avolumes\x12Z\n" +
	"\x18persistent_volume_claims\x18\x10 \x03(\v2 .kubemodel.PersistentVolumeClaimR\x16persistentVolumeClaims*\xbc\x01\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROVIDER_AWS\x10\x01\x12\x10\n" +
	"\fPROVIDER_GCP\x10\x02\x12\x12\n" +
	"\x0ePROVIDER_AZURE\x10\x03\x12\x18\n" +
	"\x14PROVIDER_ON_PREMISES\x10\x04\x12\x14\n" +
	"\x10PROVIDER_ALIBABA\x10\x05\x12\x19\n" +
	"\x15PROVIDER_DIGITALOCEAN\x10\x06\x12\x13\n" +
	"\x0fPROVIDER_ORACLE\x10\aB:Z8github.com/opencost/opencost/core/pkg/model/pb/kubemodelb\x06proto3"

var (
	file_kubemodel_cluster_proto_rawDescOnce sync.Once
	file_kubemodel_cluster_proto_rawDescData []byte
)

func file_kubemodel_cluster_proto_rawDescGZIP() []byte {
	file_kubemodel_cluster_proto_rawDescOnce.Do(func() {
		file_kubemodel_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubemodel_cluster_proto_rawDesc), len(file_kubemodel_cluster_proto_rawDesc)))
	})
	return file_kubemodel_cluster_proto_rawDescData
}

var file_kubemodel_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kubemodel_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kubemodel_cluster_proto_goTypes = []any{
	(Provider)(0),                 // 0: kubemodel.Provider
	(*Cluster)(nil),               // 1: kubemodel.Cluster
	(*pb.Window)(nil),             // 2: model.Window
	(*Container)(nil),             // 3: kubemodel.Container
	(*Controller)(nil),            // 4: kubemodel.Controller
	(*GPUDevice)(nil),             // 5: kubemodel.GPUDevice
	(*GPUUsage)(nil),              // 6: kubemodel.GPUUsage
	(*Namespace)(nil),             // 7: kubemodel.Namespace
	(*Service)(nil),               // 8: kubemodel.Service
	(*Node)(nil),                  // 9: kubemodel.Node
	(*Pod)(nil),                   // 10: kubemodel.Pod
	(*Volume)(nil),                // 11: kubemodel.Volume
	(*PersistentVolumeClaim)(nil), // 12: kubemodel.PersistentVolumeClaim
}
var file_kubemodel_cluster_proto_depIdxs = []int32{
	0,  // 0: kubemodel.Cluster.provider:type_name -> kubemodel.Provider
	2,  // 1: kubemodel.Cluster.window:type_name -> model.Window
	3,  // 2: kubemodel.Cluster.containers:type_name -> kubemodel.Container
	4,  // 3: kubemodel.Cluster.controllers:type_name -> kubemodel.Controller
	5,  // 4: kubemodel.Cluster.gpu_devices:type_name -> kubemodel.GPUDevice
	6,  // 5: kubemodel.Cluster.gpu_usage:type_name -> kubemodel.GPUUsage
	7,  // 6: kubemodel.Cluster.namespaces:type_name -> kubemodel.Namespace
	8,  // 7: kubemodel.Cluster.services:type_name -> kubemodel.Service
	9,  // 8: kubemodel.Cluster.nodes:type_name -> kubemodel.Node
	10, // 9: kubemodel.Cluster.pods:type_name -> kubemodel.Pod
	11, // 10: kubemodel.Cluster.volumes:type_name -> kubemodel.Volume
	12, // 11: kubemodel.Cluster.persistent_volume_claims:type_name -> kubemodel.PersistentVolumeClaim
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_kubemodel_cluster_proto_init() }
func file_kubemodel_cluster_proto_init() {
	if File_kubemodel_cluster_proto != nil {
		return
	}
	file_kubemodel_container_proto_init()
	file_kubemodel_controller_proto_init()
	file_kubemodel_gpu_proto_init()
	file_kubemodel_namespace_proto_init()
	file_kubemodel_network_proto_init()
	file_kubemodel_node_proto_init()
	file_kubemodel_pod_proto_init()
	file_kubemodel_storage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubemodel_cluster_proto_rawDesc), len(file_kubemodel_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubemodel_cluster_proto_goTypes,
		DependencyIndexes: file_kubemodel_cluster_proto_depIdxs,
		EnumInfos:         file_kubemodel_cluster_proto_enumTypes,
		MessageInfos:      file_kubemodel_cluster_proto_msgTypes,
	}.Build()
	File_kubemodel_cluster_proto = out.File
	file_kubemodel_cluster_proto_goTypes = nil
	file_kubemodel_cluster_proto_depIdxs = nil
}
