// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: kubemodel/network.proto

package kubemodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServicePort represents a port exposed by a service
type ServicePort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	TargetPort    int32                  `protobuf:"varint,4,opt,name=targetPort,proto3" json:"targetPort,omitempty"`
	NodePort      int32                  `protobuf:"varint,5,opt,name=nodePort,proto3" json:"nodePort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePort) Reset() {
	*x = ServicePort{}
	mi := &file_kubemodel_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePort) ProtoMessage() {}

func (x *ServicePort) ProtoReflect() protoreflect.Message {
	mi := &file_kubemodel_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePort.ProtoReflect.Descriptor instead.
func (*ServicePort) Descriptor() ([]byte, []int) {
	return file_kubemodel_network_proto_rawDescGZIP(), []int{0}
}

func (x *ServicePort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicePort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServicePort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServicePort) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ServicePort) GetNodePort() int32 {
	if x != nil {
		return x.NodePort
	}
	return 0
}

// Service represents a K8s Service (allocated resource)
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	ID        string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ClusterID string `protobuf:"bytes,2,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	// Properties
	Name        string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ServiceType string            `protobuf:"bytes,4,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Ports       []*ServicePort    `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	Labels      map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource lifecycle (only when different from cluster window)
	CreationTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=creationTime,proto3,oneof" json:"creationTime,omitempty"`
	DeletionTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deletionTime,proto3,oneof" json:"deletionTime,omitempty"`
	// Usage metrics
	// Network transfer bytes sent through this service
	NetworkTransferBytes int64 `protobuf:"varint,10,opt,name=networkTransferBytes,proto3" json:"networkTransferBytes,omitempty"`
	// Network bytes received through this service
	NetworkReceiveBytes int64 `protobuf:"varint,11,opt,name=networkReceiveBytes,proto3" json:"networkReceiveBytes,omitempty"`
	// Diagnostic information about this resource
	Diagnostic    *DiagnosticResult `protobuf:"bytes,99,opt,name=diagnostic,proto3,oneof" json:"diagnostic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_kubemodel_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_kubemodel_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_kubemodel_network_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Service) GetClusterID() string {
	if x != nil {
		return x.ClusterID
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *Service) GetPorts() []*ServicePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Service) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Service) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Service) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Service) GetDeletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTime
	}
	return nil
}

func (x *Service) GetNetworkTransferBytes() int64 {
	if x != nil {
		return x.NetworkTransferBytes
	}
	return 0
}

func (x *Service) GetNetworkReceiveBytes() int64 {
	if x != nil {
		return x.NetworkReceiveBytes
	}
	return 0
}

func (x *Service) GetDiagnostic() *DiagnosticResult {
	if x != nil {
		return x.Diagnostic
	}
	return nil
}

var File_kubemodel_network_proto protoreflect.FileDescriptor

const file_kubemodel_network_proto_rawDesc = "" +
	"\n" +
	"\x17kubemodel/network.proto\x12\tkubemodel\x1a\x1akubemodel/diagnostic.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x01\n" +
	"\vServicePort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1e\n" +
	"\n" +
	"targetPort\x18\x04 \x01(\x05R\n" +
	"targetPort\x12\x1a\n" +
	"\bnodePort\x18\x05 \x01(\x05R\bnodePort\"\xf8\x05\n" +
	"\aService\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1c\n" +
	"\tclusterID\x18\x02 \x01(\tR\tclusterID\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vserviceType\x18\x04 \x01(\tR\vserviceType\x12,\n" +
	"\x05ports\x18\x05 \x03(\v2\x16.kubemodel.ServicePortR\x05ports\x126\n" +
	"\x06labels\x18\x06 \x03(\v2\x1e.kubemodel.Service.LabelsEntryR\x06labels\x12E\n" +
	"\vannotations\x18\a \x03(\v2#.kubemodel.Service.AnnotationsEntryR\vannotations\x12C\n" +
	"\fcreationTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\fcreationTime\x88\x01\x01\x12C\n" +
	"\fdeletionTime\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x01R\fdeletionTime\x88\x01\x01\x122\n" +
	"\x14networkTransferBytes\x18\n" +
	" \x01(\x03R\x14networkTransferBytes\x120\n" +
	"\x13networkReceiveBytes\x18\v \x01(\x03R\x13networkReceiveBytes\x12@\n" +
	"\n" +
	"diagnostic\x18c \x01(\v2\x1b.kubemodel.DiagnosticResultH\x02R\n" +
	"diagnostic\x88\x01\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_creationTimeB\x0f\n" +
	"\r_deletionTimeB\r\n" +
	"\v_diagnosticB:Z8github.com/opencost/opencost/core/pkg/model/pb/kubemodelb\x06proto3"

var (
	file_kubemodel_network_proto_rawDescOnce sync.Once
	file_kubemodel_network_proto_rawDescData []byte
)

func file_kubemodel_network_proto_rawDescGZIP() []byte {
	file_kubemodel_network_proto_rawDescOnce.Do(func() {
		file_kubemodel_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubemodel_network_proto_rawDesc), len(file_kubemodel_network_proto_rawDesc)))
	})
	return file_kubemodel_network_proto_rawDescData
}

var file_kubemodel_network_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kubemodel_network_proto_goTypes = []any{
	(*ServicePort)(nil),           // 0: kubemodel.ServicePort
	(*Service)(nil),               // 1: kubemodel.Service
	nil,                           // 2: kubemodel.Service.LabelsEntry
	nil,                           // 3: kubemodel.Service.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*DiagnosticResult)(nil),      // 5: kubemodel.DiagnosticResult
}
var file_kubemodel_network_proto_depIdxs = []int32{
	0, // 0: kubemodel.Service.ports:type_name -> kubemodel.ServicePort
	2, // 1: kubemodel.Service.labels:type_name -> kubemodel.Service.LabelsEntry
	3, // 2: kubemodel.Service.annotations:type_name -> kubemodel.Service.AnnotationsEntry
	4, // 3: kubemodel.Service.creationTime:type_name -> google.protobuf.Timestamp
	4, // 4: kubemodel.Service.deletionTime:type_name -> google.protobuf.Timestamp
	5, // 5: kubemodel.Service.diagnostic:type_name -> kubemodel.DiagnosticResult
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_kubemodel_network_proto_init() }
func file_kubemodel_network_proto_init() {
	if File_kubemodel_network_proto != nil {
		return
	}
	file_kubemodel_diagnostic_proto_init()
	file_kubemodel_network_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubemodel_network_proto_rawDesc), len(file_kubemodel_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubemodel_network_proto_goTypes,
		DependencyIndexes: file_kubemodel_network_proto_depIdxs,
		MessageInfos:      file_kubemodel_network_proto_msgTypes,
	}.Build()
	File_kubemodel_network_proto = out.File
	file_kubemodel_network_proto_goTypes = nil
	file_kubemodel_network_proto_depIdxs = nil
}
