// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: kubemodel/node.proto

package kubemodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node represents a Kubernetes worker node (provisioned resource)
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	ID        string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ClusterID string `protobuf:"bytes,2,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	// Properties
	ProviderResourceID string            `protobuf:"bytes,3,opt,name=providerResourceID,proto3" json:"providerResourceID,omitempty"`
	Name               string            `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Labels             map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations        map[string]string `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource lifecycle (only when different from cluster window)
	CreationTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=creationTime,proto3,oneof" json:"creationTime,omitempty"`
	DeletionTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deletionTime,proto3,oneof" json:"deletionTime,omitempty"`
	// Diagnostic information about this resource
	Diagnostic    *DiagnosticResult `protobuf:"bytes,99,opt,name=diagnostic,proto3,oneof" json:"diagnostic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_kubemodel_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_kubemodel_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_kubemodel_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Node) GetClusterID() string {
	if x != nil {
		return x.ClusterID
	}
	return ""
}

func (x *Node) GetProviderResourceID() string {
	if x != nil {
		return x.ProviderResourceID
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Node) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Node) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Node) GetDeletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTime
	}
	return nil
}

func (x *Node) GetDiagnostic() *DiagnosticResult {
	if x != nil {
		return x.Diagnostic
	}
	return nil
}

var File_kubemodel_node_proto protoreflect.FileDescriptor

const file_kubemodel_node_proto_rawDesc = "" +
	"\n" +
	"\x14kubemodel/node.proto\x12\tkubemodel\x1a\x1akubemodel/diagnostic.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x04\n" +
	"\x04Node\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1c\n" +
	"\tclusterID\x18\x02 \x01(\tR\tclusterID\x12.\n" +
	"\x12providerResourceID\x18\x03 \x01(\tR\x12providerResourceID\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x123\n" +
	"\x06labels\x18\x05 \x03(\v2\x1b.kubemodel.Node.LabelsEntryR\x06labels\x12B\n" +
	"\vannotations\x18\x06 \x03(\v2 .kubemodel.Node.AnnotationsEntryR\vannotations\x12C\n" +
	"\fcreationTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\fcreationTime\x88\x01\x01\x12C\n" +
	"\fdeletionTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\fdeletionTime\x88\x01\x01\x12@\n" +
	"\n" +
	"diagnostic\x18c \x01(\v2\x1b.kubemodel.DiagnosticResultH\x02R\n" +
	"diagnostic\x88\x01\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_creationTimeB\x0f\n" +
	"\r_deletionTimeB\r\n" +
	"\v_diagnosticB:Z8github.com/opencost/opencost/core/pkg/model/pb/kubemodelb\x06proto3"

var (
	file_kubemodel_node_proto_rawDescOnce sync.Once
	file_kubemodel_node_proto_rawDescData []byte
)

func file_kubemodel_node_proto_rawDescGZIP() []byte {
	file_kubemodel_node_proto_rawDescOnce.Do(func() {
		file_kubemodel_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubemodel_node_proto_rawDesc), len(file_kubemodel_node_proto_rawDesc)))
	})
	return file_kubemodel_node_proto_rawDescData
}

var file_kubemodel_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kubemodel_node_proto_goTypes = []any{
	(*Node)(nil),                  // 0: kubemodel.Node
	nil,                           // 1: kubemodel.Node.LabelsEntry
	nil,                           // 2: kubemodel.Node.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*DiagnosticResult)(nil),      // 4: kubemodel.DiagnosticResult
}
var file_kubemodel_node_proto_depIdxs = []int32{
	1, // 0: kubemodel.Node.labels:type_name -> kubemodel.Node.LabelsEntry
	2, // 1: kubemodel.Node.annotations:type_name -> kubemodel.Node.AnnotationsEntry
	3, // 2: kubemodel.Node.creationTime:type_name -> google.protobuf.Timestamp
	3, // 3: kubemodel.Node.deletionTime:type_name -> google.protobuf.Timestamp
	4, // 4: kubemodel.Node.diagnostic:type_name -> kubemodel.DiagnosticResult
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kubemodel_node_proto_init() }
func file_kubemodel_node_proto_init() {
	if File_kubemodel_node_proto != nil {
		return
	}
	file_kubemodel_diagnostic_proto_init()
	file_kubemodel_node_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubemodel_node_proto_rawDesc), len(file_kubemodel_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubemodel_node_proto_goTypes,
		DependencyIndexes: file_kubemodel_node_proto_depIdxs,
		MessageInfos:      file_kubemodel_node_proto_msgTypes,
	}.Build()
	File_kubemodel_node_proto = out.File
	file_kubemodel_node_proto_goTypes = nil
	file_kubemodel_node_proto_depIdxs = nil
}
