// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: kubemodel/pod.proto

package kubemodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pod represents a Kubernetes pod (allocated resource grouping)
type Pod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	ID           string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NamespaceID  string `protobuf:"bytes,2,opt,name=namespaceID,proto3" json:"namespaceID,omitempty"`
	ControllerID string `protobuf:"bytes,3,opt,name=controllerID,proto3" json:"controllerID,omitempty"`
	NodeID       string `protobuf:"bytes,4,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	// Properties
	Name        string            `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Labels      map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource lifecycle (only when different from cluster window)
	CreationTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=creationTime,proto3,oneof" json:"creationTime,omitempty"`
	DeletionTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deletionTime,proto3,oneof" json:"deletionTime,omitempty"`
	// Usage metrics
	// CPU usage in core-hours
	CpuCoreHours float32 `protobuf:"fixed32,10,opt,name=cpuCoreHours,proto3" json:"cpuCoreHours,omitempty"`
	// CPU request average in cores
	CpuCoreRequestAverage float32 `protobuf:"fixed32,11,opt,name=cpuCoreRequestAverage,proto3" json:"cpuCoreRequestAverage,omitempty"`
	// CPU usage average in cores
	CpuCoreUsageAverage float32 `protobuf:"fixed32,12,opt,name=cpuCoreUsageAverage,proto3" json:"cpuCoreUsageAverage,omitempty"`
	// CPU usage max in cores
	CpuCoreUsageMax float32 `protobuf:"fixed32,13,opt,name=cpuCoreUsageMax,proto3" json:"cpuCoreUsageMax,omitempty"`
	// RAM usage in byte-hours
	RamByteHours int64 `protobuf:"varint,14,opt,name=ramByteHours,proto3" json:"ramByteHours,omitempty"`
	// RAM request average in bytes
	RamBytesRequestAverage int64 `protobuf:"varint,15,opt,name=ramBytesRequestAverage,proto3" json:"ramBytesRequestAverage,omitempty"`
	// RAM usage average in bytes
	RamBytesUsageAverage int64 `protobuf:"varint,16,opt,name=ramBytesUsageAverage,proto3" json:"ramBytesUsageAverage,omitempty"`
	// RAM usage max in bytes
	RamBytesUsageMax int64 `protobuf:"varint,17,opt,name=ramBytesUsageMax,proto3" json:"ramBytesUsageMax,omitempty"`
	// Storage usage in byte-hours
	StorageByteHours int64 `protobuf:"varint,18,opt,name=storageByteHours,proto3" json:"storageByteHours,omitempty"`
	// Network transfer bytes sent
	NetworkTransferBytes int64 `protobuf:"varint,19,opt,name=networkTransferBytes,proto3" json:"networkTransferBytes,omitempty"`
	// Network bytes received
	NetworkReceiveBytes int64 `protobuf:"varint,20,opt,name=networkReceiveBytes,proto3" json:"networkReceiveBytes,omitempty"`
	// Diagnostic information about this resource
	Diagnostic    *DiagnosticResult `protobuf:"bytes,99,opt,name=diagnostic,proto3,oneof" json:"diagnostic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_kubemodel_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_kubemodel_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_kubemodel_pod_proto_rawDescGZIP(), []int{0}
}

func (x *Pod) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Pod) GetNamespaceID() string {
	if x != nil {
		return x.NamespaceID
	}
	return ""
}

func (x *Pod) GetControllerID() string {
	if x != nil {
		return x.ControllerID
	}
	return ""
}

func (x *Pod) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Pod) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Pod) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Pod) GetDeletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTime
	}
	return nil
}

func (x *Pod) GetCpuCoreHours() float32 {
	if x != nil {
		return x.CpuCoreHours
	}
	return 0
}

func (x *Pod) GetCpuCoreRequestAverage() float32 {
	if x != nil {
		return x.CpuCoreRequestAverage
	}
	return 0
}

func (x *Pod) GetCpuCoreUsageAverage() float32 {
	if x != nil {
		return x.CpuCoreUsageAverage
	}
	return 0
}

func (x *Pod) GetCpuCoreUsageMax() float32 {
	if x != nil {
		return x.CpuCoreUsageMax
	}
	return 0
}

func (x *Pod) GetRamByteHours() int64 {
	if x != nil {
		return x.RamByteHours
	}
	return 0
}

func (x *Pod) GetRamBytesRequestAverage() int64 {
	if x != nil {
		return x.RamBytesRequestAverage
	}
	return 0
}

func (x *Pod) GetRamBytesUsageAverage() int64 {
	if x != nil {
		return x.RamBytesUsageAverage
	}
	return 0
}

func (x *Pod) GetRamBytesUsageMax() int64 {
	if x != nil {
		return x.RamBytesUsageMax
	}
	return 0
}

func (x *Pod) GetStorageByteHours() int64 {
	if x != nil {
		return x.StorageByteHours
	}
	return 0
}

func (x *Pod) GetNetworkTransferBytes() int64 {
	if x != nil {
		return x.NetworkTransferBytes
	}
	return 0
}

func (x *Pod) GetNetworkReceiveBytes() int64 {
	if x != nil {
		return x.NetworkReceiveBytes
	}
	return 0
}

func (x *Pod) GetDiagnostic() *DiagnosticResult {
	if x != nil {
		return x.Diagnostic
	}
	return nil
}

var File_kubemodel_pod_proto protoreflect.FileDescriptor

const file_kubemodel_pod_proto_rawDesc = "" +
	"\n" +
	"\x13kubemodel/pod.proto\x12\tkubemodel\x1a\x1akubemodel/diagnostic.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\b\n" +
	"\x03Pod\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12 \n" +
	"\vnamespaceID\x18\x02 \x01(\tR\vnamespaceID\x12\"\n" +
	"\fcontrollerID\x18\x03 \x01(\tR\fcontrollerID\x12\x16\n" +
	"\x06nodeID\x18\x04 \x01(\tR\x06nodeID\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x122\n" +
	"\x06labels\x18\x06 \x03(\v2\x1a.kubemodel.Pod.LabelsEntryR\x06labels\x12A\n" +
	"\vannotations\x18\a \x03(\v2\x1f.kubemodel.Pod.AnnotationsEntryR\vannotations\x12C\n" +
	"\fcreationTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\fcreationTime\x88\x01\x01\x12C\n" +
	"\fdeletionTime\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x01R\fdeletionTime\x88\x01\x01\x12\"\n" +
	"\fcpuCoreHours\x18\n" +
	" \x01(\x02R\fcpuCoreHours\x124\n" +
	"\x15cpuCoreRequestAverage\x18\v \x01(\x02R\x15cpuCoreRequestAverage\x120\n" +
	"\x13cpuCoreUsageAverage\x18\f \x01(\x02R\x13cpuCoreUsageAverage\x12(\n" +
	"\x0fcpuCoreUsageMax\x18\r \x01(\x02R\x0fcpuCoreUsageMax\x12\"\n" +
	"\framByteHours\x18\x0e \x01(\x03R\framByteHours\x126\n" +
	"\x16ramBytesRequestAverage\x18\x0f \x01(\x03R\x16ramBytesRequestAverage\x122\n" +
	"\x14ramBytesUsageAverage\x18\x10 \x01(\x03R\x14ramBytesUsageAverage\x12*\n" +
	"\x10ramBytesUsageMax\x18\x11 \x01(\x03R\x10ramBytesUsageMax\x12*\n" +
	"\x10storageByteHours\x18\x12 \x01(\x03R\x10storageByteHours\x122\n" +
	"\x14networkTransferBytes\x18\x13 \x01(\x03R\x14networkTransferBytes\x120\n" +
	"\x13networkReceiveBytes\x18\x14 \x01(\x03R\x13networkReceiveBytes\x12@\n" +
	"\n" +
	"diagnostic\x18c \x01(\v2\x1b.kubemodel.DiagnosticResultH\x02R\n" +
	"diagnostic\x88\x01\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_creationTimeB\x0f\n" +
	"\r_deletionTimeB\r\n" +
	"\v_diagnosticB:Z8github.com/opencost/opencost/core/pkg/model/pb/kubemodelb\x06proto3"

var (
	file_kubemodel_pod_proto_rawDescOnce sync.Once
	file_kubemodel_pod_proto_rawDescData []byte
)

func file_kubemodel_pod_proto_rawDescGZIP() []byte {
	file_kubemodel_pod_proto_rawDescOnce.Do(func() {
		file_kubemodel_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubemodel_pod_proto_rawDesc), len(file_kubemodel_pod_proto_rawDesc)))
	})
	return file_kubemodel_pod_proto_rawDescData
}

var file_kubemodel_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kubemodel_pod_proto_goTypes = []any{
	(*Pod)(nil),                   // 0: kubemodel.Pod
	nil,                           // 1: kubemodel.Pod.LabelsEntry
	nil,                           // 2: kubemodel.Pod.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*DiagnosticResult)(nil),      // 4: kubemodel.DiagnosticResult
}
var file_kubemodel_pod_proto_depIdxs = []int32{
	1, // 0: kubemodel.Pod.labels:type_name -> kubemodel.Pod.LabelsEntry
	2, // 1: kubemodel.Pod.annotations:type_name -> kubemodel.Pod.AnnotationsEntry
	3, // 2: kubemodel.Pod.creationTime:type_name -> google.protobuf.Timestamp
	3, // 3: kubemodel.Pod.deletionTime:type_name -> google.protobuf.Timestamp
	4, // 4: kubemodel.Pod.diagnostic:type_name -> kubemodel.DiagnosticResult
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kubemodel_pod_proto_init() }
func file_kubemodel_pod_proto_init() {
	if File_kubemodel_pod_proto != nil {
		return
	}
	file_kubemodel_diagnostic_proto_init()
	file_kubemodel_pod_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubemodel_pod_proto_rawDesc), len(file_kubemodel_pod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubemodel_pod_proto_goTypes,
		DependencyIndexes: file_kubemodel_pod_proto_depIdxs,
		MessageInfos:      file_kubemodel_pod_proto_msgTypes,
	}.Build()
	File_kubemodel_pod_proto = out.File
	file_kubemodel_pod_proto_goTypes = nil
	file_kubemodel_pod_proto_depIdxs = nil
}
