// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: datamodel/compute.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GPUDevice represents a GPU device with DCGM integration (provisioned resource)
type GPUDevice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // NVIDIA GPU UUID (hardware identifier)
	NodeID string `protobuf:"bytes,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	// Properties
	DeviceNumber int32             `protobuf:"varint,3,opt,name=DeviceNumber,proto3" json:"DeviceNumber,omitempty"`
	ModelName    string            `protobuf:"bytes,4,opt,name=ModelName,proto3" json:"ModelName,omitempty"`
	Labels       map[string]string `protobuf:"bytes,5,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations  map[string]string `protobuf:"bytes,6,rep,name=Annotations,proto3" json:"Annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource lifecycle (only when different from cluster window)
	Lifetime *ResourceLifetime `protobuf:"bytes,7,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	// Data (usage metrics available from DCGM)
	UsageAvg float32 `protobuf:"fixed32,8,opt,name=UsageAvg,proto3" json:"UsageAvg,omitempty"`
	UsageMax float32 `protobuf:"fixed32,9,opt,name=UsageMax,proto3" json:"UsageMax,omitempty"`
	// GPU sharing information (needed for cost allocation)
	IsShared        bool    `protobuf:"varint,12,opt,name=isShared,proto3" json:"isShared,omitempty"`
	SharePercentage float32 `protobuf:"fixed32,13,opt,name=sharePercentage,proto3" json:"sharePercentage,omitempty"`
	// GPU cost data (optional - only populated for cost-enabled exports)
	Cost *AllocationCost `protobuf:"bytes,10,opt,name=cost,proto3" json:"cost,omitempty"`
	// Cost attribution for this GPU device
	CostAttribution *CostAttribution `protobuf:"bytes,11,opt,name=costAttribution,proto3" json:"costAttribution,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GPUDevice) Reset() {
	*x = GPUDevice{}
	mi := &file_datamodel_compute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUDevice) ProtoMessage() {}

func (x *GPUDevice) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_compute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUDevice.ProtoReflect.Descriptor instead.
func (*GPUDevice) Descriptor() ([]byte, []int) {
	return file_datamodel_compute_proto_rawDescGZIP(), []int{0}
}

func (x *GPUDevice) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GPUDevice) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *GPUDevice) GetDeviceNumber() int32 {
	if x != nil {
		return x.DeviceNumber
	}
	return 0
}

func (x *GPUDevice) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GPUDevice) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GPUDevice) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *GPUDevice) GetLifetime() *ResourceLifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *GPUDevice) GetUsageAvg() float32 {
	if x != nil {
		return x.UsageAvg
	}
	return 0
}

func (x *GPUDevice) GetUsageMax() float32 {
	if x != nil {
		return x.UsageMax
	}
	return 0
}

func (x *GPUDevice) GetIsShared() bool {
	if x != nil {
		return x.IsShared
	}
	return false
}

func (x *GPUDevice) GetSharePercentage() float32 {
	if x != nil {
		return x.SharePercentage
	}
	return 0
}

func (x *GPUDevice) GetCost() *AllocationCost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *GPUDevice) GetCostAttribution() *CostAttribution {
	if x != nil {
		return x.CostAttribution
	}
	return nil
}

var File_datamodel_compute_proto protoreflect.FileDescriptor

const file_datamodel_compute_proto_rawDesc = "" +
	"\n" +
	"\x17datamodel/compute.proto\x12\fdatamodel.v2\x1a\x16datamodel/common.proto\x1a\x15datamodel/costs.proto\"\xae\x05\n" +
	"\tGPUDevice\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06NodeID\x18\x02 \x01(\tR\x06NodeID\x12\"\n" +
	"\fDeviceNumber\x18\x03 \x01(\x05R\fDeviceNumber\x12\x1c\n" +
	"\tModelName\x18\x04 \x01(\tR\tModelName\x12;\n" +
	"\x06Labels\x18\x05 \x03(\v2#.datamodel.v2.GPUDevice.LabelsEntryR\x06Labels\x12J\n" +
	"\vAnnotations\x18\x06 \x03(\v2(.datamodel.v2.GPUDevice.AnnotationsEntryR\vAnnotations\x12:\n" +
	"\blifetime\x18\a \x01(\v2\x1e.datamodel.v2.ResourceLifetimeR\blifetime\x12\x1a\n" +
	"\bUsageAvg\x18\b \x01(\x02R\bUsageAvg\x12\x1a\n" +
	"\bUsageMax\x18\t \x01(\x02R\bUsageMax\x12\x1a\n" +
	"\bisShared\x18\f \x01(\bR\bisShared\x12(\n" +
	"\x0fsharePercentage\x18\r \x01(\x02R\x0fsharePercentage\x120\n" +
	"\x04cost\x18\n" +
	" \x01(\v2\x1c.datamodel.v2.AllocationCostR\x04cost\x12G\n" +
	"\x0fcostAttribution\x18\v \x01(\v2\x1d.datamodel.v2.CostAttributionR\x0fcostAttribution\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B3Z1github.com/opencost/opencost/core/pkg/model/pb;pbb\x06proto3"

var (
	file_datamodel_compute_proto_rawDescOnce sync.Once
	file_datamodel_compute_proto_rawDescData []byte
)

func file_datamodel_compute_proto_rawDescGZIP() []byte {
	file_datamodel_compute_proto_rawDescOnce.Do(func() {
		file_datamodel_compute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datamodel_compute_proto_rawDesc), len(file_datamodel_compute_proto_rawDesc)))
	})
	return file_datamodel_compute_proto_rawDescData
}

var file_datamodel_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_datamodel_compute_proto_goTypes = []any{
	(*GPUDevice)(nil),        // 0: datamodel.v2.GPUDevice
	nil,                      // 1: datamodel.v2.GPUDevice.LabelsEntry
	nil,                      // 2: datamodel.v2.GPUDevice.AnnotationsEntry
	(*ResourceLifetime)(nil), // 3: datamodel.v2.ResourceLifetime
	(*AllocationCost)(nil),   // 4: datamodel.v2.AllocationCost
	(*CostAttribution)(nil),  // 5: datamodel.v2.CostAttribution
}
var file_datamodel_compute_proto_depIdxs = []int32{
	1, // 0: datamodel.v2.GPUDevice.Labels:type_name -> datamodel.v2.GPUDevice.LabelsEntry
	2, // 1: datamodel.v2.GPUDevice.Annotations:type_name -> datamodel.v2.GPUDevice.AnnotationsEntry
	3, // 2: datamodel.v2.GPUDevice.lifetime:type_name -> datamodel.v2.ResourceLifetime
	4, // 3: datamodel.v2.GPUDevice.cost:type_name -> datamodel.v2.AllocationCost
	5, // 4: datamodel.v2.GPUDevice.costAttribution:type_name -> datamodel.v2.CostAttribution
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_datamodel_compute_proto_init() }
func file_datamodel_compute_proto_init() {
	if File_datamodel_compute_proto != nil {
		return
	}
	file_datamodel_common_proto_init()
	file_datamodel_costs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datamodel_compute_proto_rawDesc), len(file_datamodel_compute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datamodel_compute_proto_goTypes,
		DependencyIndexes: file_datamodel_compute_proto_depIdxs,
		MessageInfos:      file_datamodel_compute_proto_msgTypes,
	}.Build()
	File_datamodel_compute_proto = out.File
	file_datamodel_compute_proto_goTypes = nil
	file_datamodel_compute_proto_depIdxs = nil
}
