// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: datamodel/costs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CostMetrics represents different cost accounting methods
// Mirrors OpenCost's multiple cost calculation approaches
type CostMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List cost (raw cost without discounts)
	ListCost float32 `protobuf:"fixed32,1,opt,name=listCost,proto3" json:"listCost,omitempty"`
	// Net cost (list cost minus discounts)
	NetCost float32 `protobuf:"fixed32,2,opt,name=netCost,proto3" json:"netCost,omitempty"`
	// Amortized net cost (includes reserved instance amortization)
	AmortizedNetCost float32 `protobuf:"fixed32,3,opt,name=amortizedNetCost,proto3" json:"amortizedNetCost,omitempty"`
	// Invoiced cost (actual billed amount)
	InvoicedCost float32 `protobuf:"fixed32,4,opt,name=invoicedCost,proto3" json:"invoicedCost,omitempty"`
	// Amortized cost (list cost with RI amortization)
	AmortizedCost float32 `protobuf:"fixed32,5,opt,name=amortizedCost,proto3" json:"amortizedCost,omitempty"`
	// Percentage of cost attributed to Kubernetes workloads
	KubernetesPercent float32 `protobuf:"fixed32,6,opt,name=kubernetesPercent,proto3" json:"kubernetesPercent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CostMetrics) Reset() {
	*x = CostMetrics{}
	mi := &file_datamodel_costs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostMetrics) ProtoMessage() {}

func (x *CostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostMetrics.ProtoReflect.Descriptor instead.
func (*CostMetrics) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{0}
}

func (x *CostMetrics) GetListCost() float32 {
	if x != nil {
		return x.ListCost
	}
	return 0
}

func (x *CostMetrics) GetNetCost() float32 {
	if x != nil {
		return x.NetCost
	}
	return 0
}

func (x *CostMetrics) GetAmortizedNetCost() float32 {
	if x != nil {
		return x.AmortizedNetCost
	}
	return 0
}

func (x *CostMetrics) GetInvoicedCost() float32 {
	if x != nil {
		return x.InvoicedCost
	}
	return 0
}

func (x *CostMetrics) GetAmortizedCost() float32 {
	if x != nil {
		return x.AmortizedCost
	}
	return 0
}

func (x *CostMetrics) GetKubernetesPercent() float32 {
	if x != nil {
		return x.KubernetesPercent
	}
	return 0
}

// ResourceCost represents cost for a specific resource type
// Follows OpenCost's base cost + adjustment pattern
type ResourceCost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base cost for this resource
	Base *CostMetrics `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Cost adjustments (reconciliation, manual adjustments)
	Adjustment *CostMetrics `protobuf:"bytes,2,opt,name=adjustment,proto3" json:"adjustment,omitempty"`
	// Resource usage hours (e.g., CPUCoreHours, RAMByteHours)
	UsageHours float32 `protobuf:"fixed32,3,opt,name=usageHours,proto3" json:"usageHours,omitempty"`
	// Requested resource average (for over/under-provisioning analysis)
	RequestAverage float32 `protobuf:"fixed32,4,opt,name=requestAverage,proto3" json:"requestAverage,omitempty"`
	// Actual usage average (for utilization analysis)
	UsageAverage float32 `protobuf:"fixed32,5,opt,name=usageAverage,proto3" json:"usageAverage,omitempty"`
	// Idle cost portion (when resource is provisioned but unused)
	Idle          *CostMetrics `protobuf:"bytes,6,opt,name=idle,proto3" json:"idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceCost) Reset() {
	*x = ResourceCost{}
	mi := &file_datamodel_costs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCost) ProtoMessage() {}

func (x *ResourceCost) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCost.ProtoReflect.Descriptor instead.
func (*ResourceCost) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceCost) GetBase() *CostMetrics {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ResourceCost) GetAdjustment() *CostMetrics {
	if x != nil {
		return x.Adjustment
	}
	return nil
}

func (x *ResourceCost) GetUsageHours() float32 {
	if x != nil {
		return x.UsageHours
	}
	return 0
}

func (x *ResourceCost) GetRequestAverage() float32 {
	if x != nil {
		return x.RequestAverage
	}
	return 0
}

func (x *ResourceCost) GetUsageAverage() float32 {
	if x != nil {
		return x.UsageAverage
	}
	return 0
}

func (x *ResourceCost) GetIdle() *CostMetrics {
	if x != nil {
		return x.Idle
	}
	return nil
}

// DetailedNetworkCost breaks down network costs by traffic type
// Maps to OpenCost's granular network cost tracking
type DetailedNetworkCost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cross-zone network transfer costs
	CrossZone *CostMetrics `protobuf:"bytes,1,opt,name=crossZone,proto3" json:"crossZone,omitempty"`
	// Cross-region network transfer costs
	CrossRegion *CostMetrics `protobuf:"bytes,2,opt,name=crossRegion,proto3" json:"crossRegion,omitempty"`
	// Internet egress costs
	Internet *CostMetrics `protobuf:"bytes,3,opt,name=internet,proto3" json:"internet,omitempty"`
	// Network transfer bytes sent
	TransferBytes float32 `protobuf:"fixed32,4,opt,name=transferBytes,proto3" json:"transferBytes,omitempty"`
	// Network bytes received
	ReceiveBytes  float32 `protobuf:"fixed32,5,opt,name=receiveBytes,proto3" json:"receiveBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailedNetworkCost) Reset() {
	*x = DetailedNetworkCost{}
	mi := &file_datamodel_costs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedNetworkCost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedNetworkCost) ProtoMessage() {}

func (x *DetailedNetworkCost) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedNetworkCost.ProtoReflect.Descriptor instead.
func (*DetailedNetworkCost) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{2}
}

func (x *DetailedNetworkCost) GetCrossZone() *CostMetrics {
	if x != nil {
		return x.CrossZone
	}
	return nil
}

func (x *DetailedNetworkCost) GetCrossRegion() *CostMetrics {
	if x != nil {
		return x.CrossRegion
	}
	return nil
}

func (x *DetailedNetworkCost) GetInternet() *CostMetrics {
	if x != nil {
		return x.Internet
	}
	return nil
}

func (x *DetailedNetworkCost) GetTransferBytes() float32 {
	if x != nil {
		return x.TransferBytes
	}
	return 0
}

func (x *DetailedNetworkCost) GetReceiveBytes() float32 {
	if x != nil {
		return x.ReceiveBytes
	}
	return 0
}

// GPUCostDetail represents GPU-specific cost information
// Maps to OpenCost's detailed GPU allocation tracking
type GPUCostDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base GPU cost
	Resource *ResourceCost `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// GPU device information for attribution (matches GPUDevice fields)
	ID           string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`                      // References GPUDevice.ID
	ModelName    string `protobuf:"bytes,3,opt,name=ModelName,proto3" json:"ModelName,omitempty"`        // References GPUDevice.ModelName
	DeviceNumber int32  `protobuf:"varint,4,opt,name=DeviceNumber,proto3" json:"DeviceNumber,omitempty"` // References GPUDevice.DeviceNumber
	// GPU sharing information (if applicable)
	IsShared        bool    `protobuf:"varint,5,opt,name=isShared,proto3" json:"isShared,omitempty"`
	SharePercentage float32 `protobuf:"fixed32,6,opt,name=sharePercentage,proto3" json:"sharePercentage,omitempty"`
	// Usage metrics for cost correlation (from DCGM)
	UsageAvg      float32 `protobuf:"fixed32,7,opt,name=usageAvg,proto3" json:"usageAvg,omitempty"`
	UsageMax      float32 `protobuf:"fixed32,8,opt,name=usageMax,proto3" json:"usageMax,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUCostDetail) Reset() {
	*x = GPUCostDetail{}
	mi := &file_datamodel_costs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUCostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUCostDetail) ProtoMessage() {}

func (x *GPUCostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUCostDetail.ProtoReflect.Descriptor instead.
func (*GPUCostDetail) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{3}
}

func (x *GPUCostDetail) GetResource() *ResourceCost {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *GPUCostDetail) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GPUCostDetail) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GPUCostDetail) GetDeviceNumber() int32 {
	if x != nil {
		return x.DeviceNumber
	}
	return 0
}

func (x *GPUCostDetail) GetIsShared() bool {
	if x != nil {
		return x.IsShared
	}
	return false
}

func (x *GPUCostDetail) GetSharePercentage() float32 {
	if x != nil {
		return x.SharePercentage
	}
	return 0
}

func (x *GPUCostDetail) GetUsageAvg() float32 {
	if x != nil {
		return x.UsageAvg
	}
	return 0
}

func (x *GPUCostDetail) GetUsageMax() float32 {
	if x != nil {
		return x.UsageMax
	}
	return 0
}

// StorageCostDetail represents persistent volume cost information
type StorageCostDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Volume identifier
	VolumeId string `protobuf:"bytes,1,opt,name=volumeId,proto3" json:"volumeId,omitempty"`
	// Storage class
	StorageClass string `protobuf:"bytes,2,opt,name=storageClass,proto3" json:"storageClass,omitempty"`
	// Provider resource ID (for cloud storage)
	ProviderResourceId string `protobuf:"bytes,3,opt,name=providerResourceId,proto3" json:"providerResourceId,omitempty"`
	// Storage cost
	Cost *CostMetrics `protobuf:"bytes,4,opt,name=cost,proto3" json:"cost,omitempty"`
	// Storage usage in byte-hours
	ByteHours     float32 `protobuf:"fixed32,5,opt,name=byteHours,proto3" json:"byteHours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageCostDetail) Reset() {
	*x = StorageCostDetail{}
	mi := &file_datamodel_costs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageCostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageCostDetail) ProtoMessage() {}

func (x *StorageCostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageCostDetail.ProtoReflect.Descriptor instead.
func (*StorageCostDetail) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{4}
}

func (x *StorageCostDetail) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *StorageCostDetail) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *StorageCostDetail) GetProviderResourceId() string {
	if x != nil {
		return x.ProviderResourceId
	}
	return ""
}

func (x *StorageCostDetail) GetCost() *CostMetrics {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *StorageCostDetail) GetByteHours() float32 {
	if x != nil {
		return x.ByteHours
	}
	return 0
}

// LoadBalancerCostDetail represents load balancer cost information
type LoadBalancerCostDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Load balancer identifier
	LoadBalancerId string `protobuf:"bytes,1,opt,name=loadBalancerId,proto3" json:"loadBalancerId,omitempty"`
	// Associated service name
	ServiceName string `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	// Load balancer IP address
	IpAddress string `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	// Whether this is a private load balancer
	IsPrivate bool `protobuf:"varint,4,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	// Load balancer cost
	Cost *CostMetrics `protobuf:"bytes,5,opt,name=cost,proto3" json:"cost,omitempty"`
	// Hours the load balancer was active
	Hours         float32 `protobuf:"fixed32,6,opt,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBalancerCostDetail) Reset() {
	*x = LoadBalancerCostDetail{}
	mi := &file_datamodel_costs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerCostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerCostDetail) ProtoMessage() {}

func (x *LoadBalancerCostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerCostDetail.ProtoReflect.Descriptor instead.
func (*LoadBalancerCostDetail) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{5}
}

func (x *LoadBalancerCostDetail) GetLoadBalancerId() string {
	if x != nil {
		return x.LoadBalancerId
	}
	return ""
}

func (x *LoadBalancerCostDetail) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LoadBalancerCostDetail) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LoadBalancerCostDetail) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *LoadBalancerCostDetail) GetCost() *CostMetrics {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *LoadBalancerCostDetail) GetHours() float32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

// AllocationCost represents complete cost breakdown for a resource allocation
// This is the main cost container that gets embedded in resource messages
type AllocationCost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Window for this cost calculation (inherits from cluster window if not specified)
	Window *TimeWindow `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"`
	// Resource-specific costs
	Cpu *ResourceCost `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram *ResourceCost `protobuf:"bytes,3,opt,name=ram,proto3" json:"ram,omitempty"`
	// GPU costs (can have multiple GPUs)
	Gpu []*GPUCostDetail `protobuf:"bytes,4,rep,name=gpu,proto3" json:"gpu,omitempty"`
	// Storage costs (persistent volumes)
	Storage []*StorageCostDetail `protobuf:"bytes,5,rep,name=storage,proto3" json:"storage,omitempty"`
	// Network costs with detailed breakdown
	Network *DetailedNetworkCost `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	// Load balancer costs
	LoadBalancers []*LoadBalancerCostDetail `protobuf:"bytes,7,rep,name=loadBalancers,proto3" json:"loadBalancers,omitempty"`
	// Shared costs allocated to this resource
	Shared *CostMetrics `protobuf:"bytes,8,opt,name=shared,proto3" json:"shared,omitempty"`
	// External cloud costs allocated to this resource
	External *CostMetrics `protobuf:"bytes,9,opt,name=external,proto3" json:"external,omitempty"`
	// Pre-computed total cost for performance (sum of all above)
	Total         *CostMetrics `protobuf:"bytes,10,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocationCost) Reset() {
	*x = AllocationCost{}
	mi := &file_datamodel_costs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationCost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationCost) ProtoMessage() {}

func (x *AllocationCost) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationCost.ProtoReflect.Descriptor instead.
func (*AllocationCost) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{6}
}

func (x *AllocationCost) GetWindow() *TimeWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *AllocationCost) GetCpu() *ResourceCost {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *AllocationCost) GetRam() *ResourceCost {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *AllocationCost) GetGpu() []*GPUCostDetail {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *AllocationCost) GetStorage() []*StorageCostDetail {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *AllocationCost) GetNetwork() *DetailedNetworkCost {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *AllocationCost) GetLoadBalancers() []*LoadBalancerCostDetail {
	if x != nil {
		return x.LoadBalancers
	}
	return nil
}

func (x *AllocationCost) GetShared() *CostMetrics {
	if x != nil {
		return x.Shared
	}
	return nil
}

func (x *AllocationCost) GetExternal() *CostMetrics {
	if x != nil {
		return x.External
	}
	return nil
}

func (x *AllocationCost) GetTotal() *CostMetrics {
	if x != nil {
		return x.Total
	}
	return nil
}

// CostAttribution represents hierarchical cost attribution information
// Maps to OpenCost's AllocationProperties for cost attribution
type CostAttribution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cluster-level attribution
	Cluster    string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	ProviderId string `protobuf:"bytes,2,opt,name=providerId,proto3" json:"providerId,omitempty"`
	// Node-level attribution
	Node string `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	// Namespace-level attribution
	Namespace            string            `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NamespaceLabels      map[string]string `protobuf:"bytes,5,rep,name=namespaceLabels,proto3" json:"namespaceLabels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NamespaceAnnotations map[string]string `protobuf:"bytes,6,rep,name=namespaceAnnotations,proto3" json:"namespaceAnnotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Workload-level attribution
	Controller     string `protobuf:"bytes,7,opt,name=controller,proto3" json:"controller,omitempty"`
	ControllerKind string `protobuf:"bytes,8,opt,name=controllerKind,proto3" json:"controllerKind,omitempty"` // deployment, statefulset, daemonset, job
	// Pod-level attribution
	Pod string `protobuf:"bytes,9,opt,name=pod,proto3" json:"pod,omitempty"`
	// Container-level attribution
	Container string `protobuf:"bytes,10,opt,name=container,proto3" json:"container,omitempty"`
	// Service-level attribution
	Services []string `protobuf:"bytes,11,rep,name=services,proto3" json:"services,omitempty"`
	// Custom attribution
	Labels        map[string]string `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string `protobuf:"bytes,13,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostAttribution) Reset() {
	*x = CostAttribution{}
	mi := &file_datamodel_costs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostAttribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostAttribution) ProtoMessage() {}

func (x *CostAttribution) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostAttribution.ProtoReflect.Descriptor instead.
func (*CostAttribution) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{7}
}

func (x *CostAttribution) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *CostAttribution) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CostAttribution) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *CostAttribution) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CostAttribution) GetNamespaceLabels() map[string]string {
	if x != nil {
		return x.NamespaceLabels
	}
	return nil
}

func (x *CostAttribution) GetNamespaceAnnotations() map[string]string {
	if x != nil {
		return x.NamespaceAnnotations
	}
	return nil
}

func (x *CostAttribution) GetController() string {
	if x != nil {
		return x.Controller
	}
	return ""
}

func (x *CostAttribution) GetControllerKind() string {
	if x != nil {
		return x.ControllerKind
	}
	return ""
}

func (x *CostAttribution) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *CostAttribution) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *CostAttribution) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *CostAttribution) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CostAttribution) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// SharedCostAllocation represents shared/overhead costs
// For costs that need to be distributed across multiple resources
type SharedCostAllocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for the shared cost pool
	CostPoolId string `protobuf:"bytes,1,opt,name=costPoolId,proto3" json:"costPoolId,omitempty"`
	// Name/description of the shared cost
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Total shared cost metrics
	TotalCost *CostMetrics `protobuf:"bytes,3,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	// Sharing algorithm used (weighted, even, proportional)
	SharingMethod string `protobuf:"bytes,4,opt,name=sharingMethod,proto3" json:"sharingMethod,omitempty"`
	// Window for this shared cost
	Window *TimeWindow `protobuf:"bytes,5,opt,name=window,proto3" json:"window,omitempty"`
	// Cost attribution for this shared cost
	Attribution   *CostAttribution `protobuf:"bytes,6,opt,name=attribution,proto3" json:"attribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedCostAllocation) Reset() {
	*x = SharedCostAllocation{}
	mi := &file_datamodel_costs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedCostAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedCostAllocation) ProtoMessage() {}

func (x *SharedCostAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedCostAllocation.ProtoReflect.Descriptor instead.
func (*SharedCostAllocation) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{8}
}

func (x *SharedCostAllocation) GetCostPoolId() string {
	if x != nil {
		return x.CostPoolId
	}
	return ""
}

func (x *SharedCostAllocation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SharedCostAllocation) GetTotalCost() *CostMetrics {
	if x != nil {
		return x.TotalCost
	}
	return nil
}

func (x *SharedCostAllocation) GetSharingMethod() string {
	if x != nil {
		return x.SharingMethod
	}
	return ""
}

func (x *SharedCostAllocation) GetWindow() *TimeWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *SharedCostAllocation) GetAttribution() *CostAttribution {
	if x != nil {
		return x.Attribution
	}
	return nil
}

// ExternalCostAllocation represents external cloud service costs
// For costs from cloud billing APIs not directly tied to K8s resources
type ExternalCostAllocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider and service information
	Provider        Provider `protobuf:"varint,1,opt,name=provider,proto3,enum=datamodel.v2.Provider" json:"provider,omitempty"`
	ServiceName     string   `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceCategory string   `protobuf:"bytes,3,opt,name=serviceCategory,proto3" json:"serviceCategory,omitempty"`
	// External cost metrics
	Cost *CostMetrics `protobuf:"bytes,4,opt,name=cost,proto3" json:"cost,omitempty"`
	// Window for this external cost
	Window *TimeWindow `protobuf:"bytes,5,opt,name=window,proto3" json:"window,omitempty"`
	// Attribution information (may be partial)
	Attribution *CostAttribution `protobuf:"bytes,6,opt,name=attribution,proto3" json:"attribution,omitempty"`
	// Provider-specific metadata
	ProviderMetadata map[string]string `protobuf:"bytes,7,rep,name=providerMetadata,proto3" json:"providerMetadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExternalCostAllocation) Reset() {
	*x = ExternalCostAllocation{}
	mi := &file_datamodel_costs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCostAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCostAllocation) ProtoMessage() {}

func (x *ExternalCostAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_costs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCostAllocation.ProtoReflect.Descriptor instead.
func (*ExternalCostAllocation) Descriptor() ([]byte, []int) {
	return file_datamodel_costs_proto_rawDescGZIP(), []int{9}
}

func (x *ExternalCostAllocation) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ExternalCostAllocation) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ExternalCostAllocation) GetServiceCategory() string {
	if x != nil {
		return x.ServiceCategory
	}
	return ""
}

func (x *ExternalCostAllocation) GetCost() *CostMetrics {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *ExternalCostAllocation) GetWindow() *TimeWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *ExternalCostAllocation) GetAttribution() *CostAttribution {
	if x != nil {
		return x.Attribution
	}
	return nil
}

func (x *ExternalCostAllocation) GetProviderMetadata() map[string]string {
	if x != nil {
		return x.ProviderMetadata
	}
	return nil
}

var File_datamodel_costs_proto protoreflect.FileDescriptor

const file_datamodel_costs_proto_rawDesc = "" +
	"\n" +
	"\x15datamodel/costs.proto\x12\fdatamodel.v2\x1a\x16datamodel/common.proto\"\xe7\x01\n" +
	"\vCostMetrics\x12\x1a\n" +
	"\blistCost\x18\x01 \x01(\x02R\blistCost\x12\x18\n" +
	"\anetCost\x18\x02 \x01(\x02R\anetCost\x12*\n" +
	"\x10amortizedNetCost\x18\x03 \x01(\x02R\x10amortizedNetCost\x12\"\n" +
	"\finvoicedCost\x18\x04 \x01(\x02R\finvoicedCost\x12$\n" +
	"\ramortizedCost\x18\x05 \x01(\x02R\ramortizedCost\x12,\n" +
	"\x11kubernetesPercent\x18\x06 \x01(\x02R\x11kubernetesPercent\"\x93\x02\n" +
	"\fResourceCost\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.datamodel.v2.CostMetricsR\x04base\x129\n" +
	"\n" +
	"adjustment\x18\x02 \x01(\v2\x19.datamodel.v2.CostMetricsR\n" +
	"adjustment\x12\x1e\n" +
	"\n" +
	"usageHours\x18\x03 \x01(\x02R\n" +
	"usageHours\x12&\n" +
	"\x0erequestAverage\x18\x04 \x01(\x02R\x0erequestAverage\x12\"\n" +
	"\fusageAverage\x18\x05 \x01(\x02R\fusageAverage\x12-\n" +
	"\x04idle\x18\x06 \x01(\v2\x19.datamodel.v2.CostMetricsR\x04idle\"\x8c\x02\n" +
	"\x13DetailedNetworkCost\x127\n" +
	"\tcrossZone\x18\x01 \x01(\v2\x19.datamodel.v2.CostMetricsR\tcrossZone\x12;\n" +
	"\vcrossRegion\x18\x02 \x01(\v2\x19.datamodel.v2.CostMetricsR\vcrossRegion\x125\n" +
	"\binternet\x18\x03 \x01(\v2\x19.datamodel.v2.CostMetricsR\binternet\x12$\n" +
	"\rtransferBytes\x18\x04 \x01(\x02R\rtransferBytes\x12\"\n" +
	"\freceiveBytes\x18\x05 \x01(\x02R\freceiveBytes\"\x97\x02\n" +
	"\rGPUCostDetail\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.datamodel.v2.ResourceCostR\bresource\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\x12\x1c\n" +
	"\tModelName\x18\x03 \x01(\tR\tModelName\x12\"\n" +
	"\fDeviceNumber\x18\x04 \x01(\x05R\fDeviceNumber\x12\x1a\n" +
	"\bisShared\x18\x05 \x01(\bR\bisShared\x12(\n" +
	"\x0fsharePercentage\x18\x06 \x01(\x02R\x0fsharePercentage\x12\x1a\n" +
	"\busageAvg\x18\a \x01(\x02R\busageAvg\x12\x1a\n" +
	"\busageMax\x18\b \x01(\x02R\busageMax\"\xd0\x01\n" +
	"\x11StorageCostDetail\x12\x1a\n" +
	"\bvolumeId\x18\x01 \x01(\tR\bvolumeId\x12\"\n" +
	"\fstorageClass\x18\x02 \x01(\tR\fstorageClass\x12.\n" +
	"\x12providerResourceId\x18\x03 \x01(\tR\x12providerResourceId\x12-\n" +
	"\x04cost\x18\x04 \x01(\v2\x19.datamodel.v2.CostMetricsR\x04cost\x12\x1c\n" +
	"\tbyteHours\x18\x05 \x01(\x02R\tbyteHours\"\xe3\x01\n" +
	"\x16LoadBalancerCostDetail\x12&\n" +
	"\x0eloadBalancerId\x18\x01 \x01(\tR\x0eloadBalancerId\x12 \n" +
	"\vserviceName\x18\x02 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tipAddress\x18\x03 \x01(\tR\tipAddress\x12\x1c\n" +
	"\tisPrivate\x18\x04 \x01(\bR\tisPrivate\x12-\n" +
	"\x04cost\x18\x05 \x01(\v2\x19.datamodel.v2.CostMetricsR\x04cost\x12\x14\n" +
	"\x05hours\x18\x06 \x01(\x02R\x05hours\"\xac\x04\n" +
	"\x0eAllocationCost\x120\n" +
	"\x06window\x18\x01 \x01(\v2\x18.datamodel.v2.TimeWindowR\x06window\x12,\n" +
	"\x03cpu\x18\x02 \x01(\v2\x1a.datamodel.v2.ResourceCostR\x03cpu\x12,\n" +
	"\x03ram\x18\x03 \x01(\v2\x1a.datamodel.v2.ResourceCostR\x03ram\x12-\n" +
	"\x03gpu\x18\x04 \x03(\v2\x1b.datamodel.v2.GPUCostDetailR\x03gpu\x129\n" +
	"\astorage\x18\x05 \x03(\v2\x1f.datamodel.v2.StorageCostDetailR\astorage\x12;\n" +
	"\anetwork\x18\x06 \x01(\v2!.datamodel.v2.DetailedNetworkCostR\anetwork\x12J\n" +
	"\rloadBalancers\x18\a \x03(\v2$.datamodel.v2.LoadBalancerCostDetailR\rloadBalancers\x121\n" +
	"\x06shared\x18\b \x01(\v2\x19.datamodel.v2.CostMetricsR\x06shared\x125\n" +
	"\bexternal\x18\t \x01(\v2\x19.datamodel.v2.CostMetricsR\bexternal\x12/\n" +
	"\x05total\x18\n" +
	" \x01(\v2\x19.datamodel.v2.CostMetricsR\x05total\"\xf9\x06\n" +
	"\x0fCostAttribution\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1e\n" +
	"\n" +
	"providerId\x18\x02 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\\\n" +
	"\x0fnamespaceLabels\x18\x05 \x03(\v22.datamodel.v2.CostAttribution.NamespaceLabelsEntryR\x0fnamespaceLabels\x12k\n" +
	"\x14namespaceAnnotations\x18\x06 \x03(\v27.datamodel.v2.CostAttribution.NamespaceAnnotationsEntryR\x14namespaceAnnotations\x12\x1e\n" +
	"\n" +
	"controller\x18\a \x01(\tR\n" +
	"controller\x12&\n" +
	"\x0econtrollerKind\x18\b \x01(\tR\x0econtrollerKind\x12\x10\n" +
	"\x03pod\x18\t \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\n" +
	" \x01(\tR\tcontainer\x12\x1a\n" +
	"\bservices\x18\v \x03(\tR\bservices\x12A\n" +
	"\x06labels\x18\f \x03(\v2).datamodel.v2.CostAttribution.LabelsEntryR\x06labels\x12P\n" +
	"\vannotations\x18\r \x03(\v2..datamodel.v2.CostAttribution.AnnotationsEntryR\vannotations\x1aB\n" +
	"\x14NamespaceLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x19NamespaceAnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\x14SharedCostAllocation\x12\x1e\n" +
	"\n" +
	"costPoolId\x18\x01 \x01(\tR\n" +
	"costPoolId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\ttotalCost\x18\x03 \x01(\v2\x19.datamodel.v2.CostMetricsR\ttotalCost\x12$\n" +
	"\rsharingMethod\x18\x04 \x01(\tR\rsharingMethod\x120\n" +
	"\x06window\x18\x05 \x01(\v2\x18.datamodel.v2.TimeWindowR\x06window\x12?\n" +
	"\vattribution\x18\x06 \x01(\v2\x1d.datamodel.v2.CostAttributionR\vattribution\"\xe7\x03\n" +
	"\x16ExternalCostAllocation\x122\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x16.datamodel.v2.ProviderR\bprovider\x12 \n" +
	"\vserviceName\x18\x02 \x01(\tR\vserviceName\x12(\n" +
	"\x0fserviceCategory\x18\x03 \x01(\tR\x0fserviceCategory\x12-\n" +
	"\x04cost\x18\x04 \x01(\v2\x19.datamodel.v2.CostMetricsR\x04cost\x120\n" +
	"\x06window\x18\x05 \x01(\v2\x18.datamodel.v2.TimeWindowR\x06window\x12?\n" +
	"\vattribution\x18\x06 \x01(\v2\x1d.datamodel.v2.CostAttributionR\vattribution\x12f\n" +
	"\x10providerMetadata\x18\a \x03(\v2:.datamodel.v2.ExternalCostAllocation.ProviderMetadataEntryR\x10providerMetadata\x1aC\n" +
	"\x15ProviderMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B3Z1github.com/opencost/opencost/core/pkg/model/pb;pbb\x06proto3"

var (
	file_datamodel_costs_proto_rawDescOnce sync.Once
	file_datamodel_costs_proto_rawDescData []byte
)

func file_datamodel_costs_proto_rawDescGZIP() []byte {
	file_datamodel_costs_proto_rawDescOnce.Do(func() {
		file_datamodel_costs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datamodel_costs_proto_rawDesc), len(file_datamodel_costs_proto_rawDesc)))
	})
	return file_datamodel_costs_proto_rawDescData
}

var file_datamodel_costs_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_datamodel_costs_proto_goTypes = []any{
	(*CostMetrics)(nil),            // 0: datamodel.v2.CostMetrics
	(*ResourceCost)(nil),           // 1: datamodel.v2.ResourceCost
	(*DetailedNetworkCost)(nil),    // 2: datamodel.v2.DetailedNetworkCost
	(*GPUCostDetail)(nil),          // 3: datamodel.v2.GPUCostDetail
	(*StorageCostDetail)(nil),      // 4: datamodel.v2.StorageCostDetail
	(*LoadBalancerCostDetail)(nil), // 5: datamodel.v2.LoadBalancerCostDetail
	(*AllocationCost)(nil),         // 6: datamodel.v2.AllocationCost
	(*CostAttribution)(nil),        // 7: datamodel.v2.CostAttribution
	(*SharedCostAllocation)(nil),   // 8: datamodel.v2.SharedCostAllocation
	(*ExternalCostAllocation)(nil), // 9: datamodel.v2.ExternalCostAllocation
	nil,                            // 10: datamodel.v2.CostAttribution.NamespaceLabelsEntry
	nil,                            // 11: datamodel.v2.CostAttribution.NamespaceAnnotationsEntry
	nil,                            // 12: datamodel.v2.CostAttribution.LabelsEntry
	nil,                            // 13: datamodel.v2.CostAttribution.AnnotationsEntry
	nil,                            // 14: datamodel.v2.ExternalCostAllocation.ProviderMetadataEntry
	(*TimeWindow)(nil),             // 15: datamodel.v2.TimeWindow
	(Provider)(0),                  // 16: datamodel.v2.Provider
}
var file_datamodel_costs_proto_depIdxs = []int32{
	0,  // 0: datamodel.v2.ResourceCost.base:type_name -> datamodel.v2.CostMetrics
	0,  // 1: datamodel.v2.ResourceCost.adjustment:type_name -> datamodel.v2.CostMetrics
	0,  // 2: datamodel.v2.ResourceCost.idle:type_name -> datamodel.v2.CostMetrics
	0,  // 3: datamodel.v2.DetailedNetworkCost.crossZone:type_name -> datamodel.v2.CostMetrics
	0,  // 4: datamodel.v2.DetailedNetworkCost.crossRegion:type_name -> datamodel.v2.CostMetrics
	0,  // 5: datamodel.v2.DetailedNetworkCost.internet:type_name -> datamodel.v2.CostMetrics
	1,  // 6: datamodel.v2.GPUCostDetail.resource:type_name -> datamodel.v2.ResourceCost
	0,  // 7: datamodel.v2.StorageCostDetail.cost:type_name -> datamodel.v2.CostMetrics
	0,  // 8: datamodel.v2.LoadBalancerCostDetail.cost:type_name -> datamodel.v2.CostMetrics
	15, // 9: datamodel.v2.AllocationCost.window:type_name -> datamodel.v2.TimeWindow
	1,  // 10: datamodel.v2.AllocationCost.cpu:type_name -> datamodel.v2.ResourceCost
	1,  // 11: datamodel.v2.AllocationCost.ram:type_name -> datamodel.v2.ResourceCost
	3,  // 12: datamodel.v2.AllocationCost.gpu:type_name -> datamodel.v2.GPUCostDetail
	4,  // 13: datamodel.v2.AllocationCost.storage:type_name -> datamodel.v2.StorageCostDetail
	2,  // 14: datamodel.v2.AllocationCost.network:type_name -> datamodel.v2.DetailedNetworkCost
	5,  // 15: datamodel.v2.AllocationCost.loadBalancers:type_name -> datamodel.v2.LoadBalancerCostDetail
	0,  // 16: datamodel.v2.AllocationCost.shared:type_name -> datamodel.v2.CostMetrics
	0,  // 17: datamodel.v2.AllocationCost.external:type_name -> datamodel.v2.CostMetrics
	0,  // 18: datamodel.v2.AllocationCost.total:type_name -> datamodel.v2.CostMetrics
	10, // 19: datamodel.v2.CostAttribution.namespaceLabels:type_name -> datamodel.v2.CostAttribution.NamespaceLabelsEntry
	11, // 20: datamodel.v2.CostAttribution.namespaceAnnotations:type_name -> datamodel.v2.CostAttribution.NamespaceAnnotationsEntry
	12, // 21: datamodel.v2.CostAttribution.labels:type_name -> datamodel.v2.CostAttribution.LabelsEntry
	13, // 22: datamodel.v2.CostAttribution.annotations:type_name -> datamodel.v2.CostAttribution.AnnotationsEntry
	0,  // 23: datamodel.v2.SharedCostAllocation.totalCost:type_name -> datamodel.v2.CostMetrics
	15, // 24: datamodel.v2.SharedCostAllocation.window:type_name -> datamodel.v2.TimeWindow
	7,  // 25: datamodel.v2.SharedCostAllocation.attribution:type_name -> datamodel.v2.CostAttribution
	16, // 26: datamodel.v2.ExternalCostAllocation.provider:type_name -> datamodel.v2.Provider
	0,  // 27: datamodel.v2.ExternalCostAllocation.cost:type_name -> datamodel.v2.CostMetrics
	15, // 28: datamodel.v2.ExternalCostAllocation.window:type_name -> datamodel.v2.TimeWindow
	7,  // 29: datamodel.v2.ExternalCostAllocation.attribution:type_name -> datamodel.v2.CostAttribution
	14, // 30: datamodel.v2.ExternalCostAllocation.providerMetadata:type_name -> datamodel.v2.ExternalCostAllocation.ProviderMetadataEntry
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_datamodel_costs_proto_init() }
func file_datamodel_costs_proto_init() {
	if File_datamodel_costs_proto != nil {
		return
	}
	file_datamodel_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datamodel_costs_proto_rawDesc), len(file_datamodel_costs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datamodel_costs_proto_goTypes,
		DependencyIndexes: file_datamodel_costs_proto_depIdxs,
		MessageInfos:      file_datamodel_costs_proto_msgTypes,
	}.Build()
	File_datamodel_costs_proto = out.File
	file_datamodel_costs_proto_goTypes = nil
	file_datamodel_costs_proto_depIdxs = nil
}
