// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: common/labels.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LabelsResponse is a grouping of LabelSets for a specific window for a type of label grouped by their source.
type LabelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of labels in the set (e.g. account_labels, namespace_labels)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// type dependent identifier for the grouping of labels most likely the cluster id or the configuration key, used
	// as part of the export path
	GroupId string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// The window for the label sets
	Window *Window `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	// Mapping of LabelSets for individual items by a unique identifier
	LabelSets     map[string]*LabelSet `protobuf:"bytes,4,rep,name=label_sets,json=labelSets,proto3" json:"label_sets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelsResponse) Reset() {
	*x = LabelsResponse{}
	mi := &file_common_labels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelsResponse) ProtoMessage() {}

func (x *LabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_labels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelsResponse.ProtoReflect.Descriptor instead.
func (*LabelsResponse) Descriptor() ([]byte, []int) {
	return file_common_labels_proto_rawDescGZIP(), []int{0}
}

func (x *LabelsResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LabelsResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *LabelsResponse) GetWindow() *Window {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *LabelsResponse) GetLabelSets() map[string]*LabelSet {
	if x != nil {
		return x.LabelSets
	}
	return nil
}

// LabelSet is an internal message meant to enable nesting maps
type LabelSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelSet) Reset() {
	*x = LabelSet{}
	mi := &file_common_labels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSet) ProtoMessage() {}

func (x *LabelSet) ProtoReflect() protoreflect.Message {
	mi := &file_common_labels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSet.ProtoReflect.Descriptor instead.
func (*LabelSet) Descriptor() ([]byte, []int) {
	return file_common_labels_proto_rawDescGZIP(), []int{1}
}

func (x *LabelSet) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_common_labels_proto protoreflect.FileDescriptor

const file_common_labels_proto_rawDesc = "" +
	"\n" +
	"\x13common/labels.proto\x12\x06common\x1a\x13common/window.proto\"\xfd\x01\n" +
	"\x0eLabelsResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12&\n" +
	"\x06window\x18\x03 \x01(\v2\x0e.common.WindowR\x06window\x12D\n" +
	"\n" +
	"label_sets\x18\x04 \x03(\v2%.common.LabelsResponse.LabelSetsEntryR\tlabelSets\x1aN\n" +
	"\x0eLabelSetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.common.LabelSetR\x05value:\x028\x01\"{\n" +
	"\bLabelSet\x124\n" +
	"\x06labels\x18\x01 \x03(\v2\x1c.common.LabelSet.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B0Z.github.com/opencost/opencost/core/pkg/model/pbb\x06proto3"

var (
	file_common_labels_proto_rawDescOnce sync.Once
	file_common_labels_proto_rawDescData []byte
)

func file_common_labels_proto_rawDescGZIP() []byte {
	file_common_labels_proto_rawDescOnce.Do(func() {
		file_common_labels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_labels_proto_rawDesc), len(file_common_labels_proto_rawDesc)))
	})
	return file_common_labels_proto_rawDescData
}

var file_common_labels_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_labels_proto_goTypes = []any{
	(*LabelsResponse)(nil), // 0: common.LabelsResponse
	(*LabelSet)(nil),       // 1: common.LabelSet
	nil,                    // 2: common.LabelsResponse.LabelSetsEntry
	nil,                    // 3: common.LabelSet.LabelsEntry
	(*Window)(nil),         // 4: common.Window
}
var file_common_labels_proto_depIdxs = []int32{
	4, // 0: common.LabelsResponse.window:type_name -> common.Window
	2, // 1: common.LabelsResponse.label_sets:type_name -> common.LabelsResponse.LabelSetsEntry
	3, // 2: common.LabelSet.labels:type_name -> common.LabelSet.LabelsEntry
	1, // 3: common.LabelsResponse.LabelSetsEntry.value:type_name -> common.LabelSet
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_labels_proto_init() }
func file_common_labels_proto_init() {
	if File_common_labels_proto != nil {
		return
	}
	file_common_window_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_labels_proto_rawDesc), len(file_common_labels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_labels_proto_goTypes,
		DependencyIndexes: file_common_labels_proto_depIdxs,
		MessageInfos:      file_common_labels_proto_msgTypes,
	}.Build()
	File_common_labels_proto = out.File
	file_common_labels_proto_goTypes = nil
	file_common_labels_proto_depIdxs = nil
}
