// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: datamodel/sources.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataSourceMetadata tracks how data was collected (for Source interface)
type DataSourceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary data source type
	PrimarySource DataSourceType `protobuf:"varint,1,opt,name=primarySource,proto3,enum=datamodel.v2.DataSourceType" json:"primarySource,omitempty"`
	// Fallback sources used if primary failed
	FallbackSources []DataSourceType `protobuf:"varint,2,rep,packed,name=fallbackSources,proto3,enum=datamodel.v2.DataSourceType" json:"fallbackSources,omitempty"`
	// Prometheus query metadata if applicable
	PrometheusInfo *PrometheusSourceInfo `protobuf:"bytes,3,opt,name=prometheusInfo,proto3" json:"prometheusInfo,omitempty"`
	// Kubernetes API metadata if applicable
	K8SApiInfo *KubernetesAPISourceInfo `protobuf:"bytes,4,opt,name=k8sApiInfo,proto3" json:"k8sApiInfo,omitempty"`
	// Data collection timestamp
	CollectedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=collectedAt,proto3" json:"collectedAt,omitempty"`
	// Collection duration in milliseconds
	CollectionDurationMs int64 `protobuf:"varint,6,opt,name=collectionDurationMs,proto3" json:"collectionDurationMs,omitempty"`
	// Collection success/failure status
	CollectionSuccess bool `protobuf:"varint,7,opt,name=collectionSuccess,proto3" json:"collectionSuccess,omitempty"`
	// Collection errors if any
	CollectionErrors []string `protobuf:"bytes,8,rep,name=collectionErrors,proto3" json:"collectionErrors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DataSourceMetadata) Reset() {
	*x = DataSourceMetadata{}
	mi := &file_datamodel_sources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceMetadata) ProtoMessage() {}

func (x *DataSourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_sources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceMetadata.ProtoReflect.Descriptor instead.
func (*DataSourceMetadata) Descriptor() ([]byte, []int) {
	return file_datamodel_sources_proto_rawDescGZIP(), []int{0}
}

func (x *DataSourceMetadata) GetPrimarySource() DataSourceType {
	if x != nil {
		return x.PrimarySource
	}
	return DataSourceType_DATA_SOURCE_UNSPECIFIED
}

func (x *DataSourceMetadata) GetFallbackSources() []DataSourceType {
	if x != nil {
		return x.FallbackSources
	}
	return nil
}

func (x *DataSourceMetadata) GetPrometheusInfo() *PrometheusSourceInfo {
	if x != nil {
		return x.PrometheusInfo
	}
	return nil
}

func (x *DataSourceMetadata) GetK8SApiInfo() *KubernetesAPISourceInfo {
	if x != nil {
		return x.K8SApiInfo
	}
	return nil
}

func (x *DataSourceMetadata) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *DataSourceMetadata) GetCollectionDurationMs() int64 {
	if x != nil {
		return x.CollectionDurationMs
	}
	return 0
}

func (x *DataSourceMetadata) GetCollectionSuccess() bool {
	if x != nil {
		return x.CollectionSuccess
	}
	return false
}

func (x *DataSourceMetadata) GetCollectionErrors() []string {
	if x != nil {
		return x.CollectionErrors
	}
	return nil
}

// Prometheus-specific source information
type PrometheusSourceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prometheus server URL used
	PrometheusUrl string `protobuf:"bytes,1,opt,name=prometheusUrl,proto3" json:"prometheusUrl,omitempty"`
	// Query used to collect this data
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Query execution time
	QueryDurationMs int64 `protobuf:"varint,3,opt,name=queryDurationMs,proto3" json:"queryDurationMs,omitempty"`
	// Number of samples returned
	SampleCount int32 `protobuf:"varint,4,opt,name=sampleCount,proto3" json:"sampleCount,omitempty"`
	// Prometheus scrape interval used
	ScrapeIntervalSeconds int32 `protobuf:"varint,5,opt,name=scrapeIntervalSeconds,proto3" json:"scrapeIntervalSeconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PrometheusSourceInfo) Reset() {
	*x = PrometheusSourceInfo{}
	mi := &file_datamodel_sources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrometheusSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrometheusSourceInfo) ProtoMessage() {}

func (x *PrometheusSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_sources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrometheusSourceInfo.ProtoReflect.Descriptor instead.
func (*PrometheusSourceInfo) Descriptor() ([]byte, []int) {
	return file_datamodel_sources_proto_rawDescGZIP(), []int{1}
}

func (x *PrometheusSourceInfo) GetPrometheusUrl() string {
	if x != nil {
		return x.PrometheusUrl
	}
	return ""
}

func (x *PrometheusSourceInfo) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PrometheusSourceInfo) GetQueryDurationMs() int64 {
	if x != nil {
		return x.QueryDurationMs
	}
	return 0
}

func (x *PrometheusSourceInfo) GetSampleCount() int32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *PrometheusSourceInfo) GetScrapeIntervalSeconds() int32 {
	if x != nil {
		return x.ScrapeIntervalSeconds
	}
	return 0
}

// Kubernetes API-specific source information
type KubernetesAPISourceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// K8s API server endpoint
	ApiServer string `protobuf:"bytes,1,opt,name=apiServer,proto3" json:"apiServer,omitempty"`
	// Resource types queried
	ResourceTypes []string `protobuf:"bytes,2,rep,name=resourceTypes,proto3" json:"resourceTypes,omitempty"`
	// Namespace scope (empty means cluster-wide)
	NamespaceScope string `protobuf:"bytes,3,opt,name=namespaceScope,proto3" json:"namespaceScope,omitempty"`
	// API version used
	ApiVersion string `protobuf:"bytes,4,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	// Field selectors used
	FieldSelectors []string `protobuf:"bytes,5,rep,name=fieldSelectors,proto3" json:"fieldSelectors,omitempty"`
	// Label selectors used
	LabelSelectors []string `protobuf:"bytes,6,rep,name=labelSelectors,proto3" json:"labelSelectors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KubernetesAPISourceInfo) Reset() {
	*x = KubernetesAPISourceInfo{}
	mi := &file_datamodel_sources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesAPISourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesAPISourceInfo) ProtoMessage() {}

func (x *KubernetesAPISourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_sources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesAPISourceInfo.ProtoReflect.Descriptor instead.
func (*KubernetesAPISourceInfo) Descriptor() ([]byte, []int) {
	return file_datamodel_sources_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesAPISourceInfo) GetApiServer() string {
	if x != nil {
		return x.ApiServer
	}
	return ""
}

func (x *KubernetesAPISourceInfo) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *KubernetesAPISourceInfo) GetNamespaceScope() string {
	if x != nil {
		return x.NamespaceScope
	}
	return ""
}

func (x *KubernetesAPISourceInfo) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *KubernetesAPISourceInfo) GetFieldSelectors() []string {
	if x != nil {
		return x.FieldSelectors
	}
	return nil
}

func (x *KubernetesAPISourceInfo) GetLabelSelectors() []string {
	if x != nil {
		return x.LabelSelectors
	}
	return nil
}

var File_datamodel_sources_proto protoreflect.FileDescriptor

const file_datamodel_sources_proto_rawDesc = "" +
	"\n" +
	"\x17datamodel/sources.proto\x12\fdatamodel.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16datamodel/common.proto\"\xff\x03\n" +
	"\x12DataSourceMetadata\x12B\n" +
	"\rprimarySource\x18\x01 \x01(\x0e2\x1c.datamodel.v2.DataSourceTypeR\rprimarySource\x12F\n" +
	"\x0ffallbackSources\x18\x02 \x03(\x0e2\x1c.datamodel.v2.DataSourceTypeR\x0ffallbackSources\x12J\n" +
	"\x0eprometheusInfo\x18\x03 \x01(\v2\".datamodel.v2.PrometheusSourceInfoR\x0eprometheusInfo\x12E\n" +
	"\n" +
	"k8sApiInfo\x18\x04 \x01(\v2%.datamodel.v2.KubernetesAPISourceInfoR\n" +
	"k8sApiInfo\x12<\n" +
	"\vcollectedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x122\n" +
	"\x14collectionDurationMs\x18\x06 \x01(\x03R\x14collectionDurationMs\x12,\n" +
	"\x11collectionSuccess\x18\a \x01(\bR\x11collectionSuccess\x12*\n" +
	"\x10collectionErrors\x18\b \x03(\tR\x10collectionErrors\"\xd4\x01\n" +
	"\x14PrometheusSourceInfo\x12$\n" +
	"\rprometheusUrl\x18\x01 \x01(\tR\rprometheusUrl\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12(\n" +
	"\x0fqueryDurationMs\x18\x03 \x01(\x03R\x0fqueryDurationMs\x12 \n" +
	"\vsampleCount\x18\x04 \x01(\x05R\vsampleCount\x124\n" +
	"\x15scrapeIntervalSeconds\x18\x05 \x01(\x05R\x15scrapeIntervalSeconds\"\xf5\x01\n" +
	"\x17KubernetesAPISourceInfo\x12\x1c\n" +
	"\tapiServer\x18\x01 \x01(\tR\tapiServer\x12$\n" +
	"\rresourceTypes\x18\x02 \x03(\tR\rresourceTypes\x12&\n" +
	"\x0enamespaceScope\x18\x03 \x01(\tR\x0enamespaceScope\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x04 \x01(\tR\n" +
	"apiVersion\x12&\n" +
	"\x0efieldSelectors\x18\x05 \x03(\tR\x0efieldSelectors\x12&\n" +
	"\x0elabelSelectors\x18\x06 \x03(\tR\x0elabelSelectorsB3Z1github.com/opencost/opencost/core/pkg/model/pb;pbb\x06proto3"

var (
	file_datamodel_sources_proto_rawDescOnce sync.Once
	file_datamodel_sources_proto_rawDescData []byte
)

func file_datamodel_sources_proto_rawDescGZIP() []byte {
	file_datamodel_sources_proto_rawDescOnce.Do(func() {
		file_datamodel_sources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datamodel_sources_proto_rawDesc), len(file_datamodel_sources_proto_rawDesc)))
	})
	return file_datamodel_sources_proto_rawDescData
}

var file_datamodel_sources_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_datamodel_sources_proto_goTypes = []any{
	(*DataSourceMetadata)(nil),      // 0: datamodel.v2.DataSourceMetadata
	(*PrometheusSourceInfo)(nil),    // 1: datamodel.v2.PrometheusSourceInfo
	(*KubernetesAPISourceInfo)(nil), // 2: datamodel.v2.KubernetesAPISourceInfo
	(DataSourceType)(0),             // 3: datamodel.v2.DataSourceType
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_datamodel_sources_proto_depIdxs = []int32{
	3, // 0: datamodel.v2.DataSourceMetadata.primarySource:type_name -> datamodel.v2.DataSourceType
	3, // 1: datamodel.v2.DataSourceMetadata.fallbackSources:type_name -> datamodel.v2.DataSourceType
	1, // 2: datamodel.v2.DataSourceMetadata.prometheusInfo:type_name -> datamodel.v2.PrometheusSourceInfo
	2, // 3: datamodel.v2.DataSourceMetadata.k8sApiInfo:type_name -> datamodel.v2.KubernetesAPISourceInfo
	4, // 4: datamodel.v2.DataSourceMetadata.collectedAt:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_datamodel_sources_proto_init() }
func file_datamodel_sources_proto_init() {
	if File_datamodel_sources_proto != nil {
		return
	}
	file_datamodel_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datamodel_sources_proto_rawDesc), len(file_datamodel_sources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datamodel_sources_proto_goTypes,
		DependencyIndexes: file_datamodel_sources_proto_depIdxs,
		MessageInfos:      file_datamodel_sources_proto_msgTypes,
	}.Build()
	File_datamodel_sources_proto = out.File
	file_datamodel_sources_proto_goTypes = nil
	file_datamodel_sources_proto_depIdxs = nil
}
