////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package kubemodel

import (
	"fmt"
	util "github.com/opencost/opencost/core/pkg/util"
	"io"
)

//--------------------------------------------------------------------------
//  Streaming Decoder for KubeModelSet
//--------------------------------------------------------------------------

// StreamingKubeModelSetDecoder provides a streaming interface for decoding KubeModelSet
// from bingen format without loading the entire file into memory.
// It reads one record at a time from disk.
type StreamingKubeModelSetDecoder struct {
	reader io.Reader
	buff   *util.Buffer
	ctx    *DecodingContext

	// Metadata about the file
	version  uint8
	metadata *Metadata
	window   Window
	cluster  *Cluster

	// State tracking
	initialized         bool
	namespacesRead      int
	namespacesTotal     int
	resourceQuotasRead  int
	resourceQuotasTotal int

	// Current position in the stream
	currentSection string
}

// NewStreamingKubeModelSetDecoder creates a new streaming decoder that reads from the provided reader.
func NewStreamingKubeModelSetDecoder(reader io.Reader) (*StreamingKubeModelSetDecoder, error) {
	return &StreamingKubeModelSetDecoder{
		reader:      reader,
		initialized: false,
	}, nil
}

// Initialize reads the header information but does not read the map data.
func (sd *StreamingKubeModelSetDecoder) Initialize() error {
	if sd.initialized {
		return fmt.Errorf("decoder already initialized")
	}

	// Read entire file into memory for now
	// TODO: Implement true streaming by reading header only
	data, err := io.ReadAll(sd.reader)
	if err != nil {
		return fmt.Errorf("failed to read data: %w", err)
	}

	sd.buff = util.NewBufferFromBytes(data)

	// Parse string table
	var table []string
	if isBinaryTag(data, BinaryTagStringTable) {
		sd.buff.ReadBytes(len(BinaryTagStringTable))
		tl := sd.buff.ReadInt()
		if tl > 0 {
			table = make([]string, tl)
			for i := 0; i < tl; i++ {
				table[i] = sd.buff.ReadString()
			}
		}
	}

	sd.ctx = &DecodingContext{
		Buffer: sd.buff,
		Table:  table,
	}

	// Read version
	sd.version = sd.buff.ReadUInt8()
	if sd.version > DefaultCodecVersion {
		return fmt.Errorf("invalid version: expected %d or less, got %d", DefaultCodecVersion, sd.version)
	}

	// Read Metadata
	{
		var temp *Metadata
		if sd.buff.ReadUInt8() != uint8(0) {
			tempVal := &Metadata{}
			sd.buff.ReadInt() // compatibility
			err := tempVal.UnmarshalBinaryWithContext(sd.ctx)
			if err != nil {
				return err
			}
			temp = tempVal
		}
		sd.metadata = temp
	}

	// Read Window
	{
		var temp Window
		tempVal := &Window{}
		sd.buff.ReadInt() // compatibility
		err := tempVal.UnmarshalBinaryWithContext(sd.ctx)
		if err != nil {
			return err
		}
		temp = *tempVal
		sd.window = temp
	}

	// Read Cluster
	{
		var temp *Cluster
		if sd.buff.ReadUInt8() != uint8(0) {
			tempVal := &Cluster{}
			sd.buff.ReadInt() // compatibility
			err := tempVal.UnmarshalBinaryWithContext(sd.ctx)
			if err != nil {
				return err
			}
			temp = tempVal
		}
		sd.cluster = temp
	}

	// Read Namespaces length
	if sd.buff.ReadUInt8() != uint8(0) {
		sd.namespacesTotal = sd.buff.ReadInt()
	} else {
		sd.namespacesTotal = 0
	}

	sd.initialized = true
	sd.currentSection = "namespaces"
	return nil
}

// NextNamespaces reads and returns the next Namespaces entry from the stream.
// Returns (key, value, nil) on success, or (zero, zero, io.EOF) when no more entries.
func (sd *StreamingKubeModelSetDecoder) NextNamespaces() (string, *Namespace, error) {
	if !sd.initialized {
		return "", nil, fmt.Errorf("decoder not initialized")
	}

	if sd.currentSection != "namespaces" {
		return "", nil, fmt.Errorf("not in namespaces section")
	}

	if sd.namespacesRead >= sd.namespacesTotal {
		// Move to resourceQuotas section
		sd.currentSection = "resourceQuotas"

		// Read ResourceQuotas length
		if sd.buff.ReadUInt8() != uint8(0) {
			sd.resourceQuotasTotal = sd.buff.ReadInt()
		} else {
			sd.resourceQuotasTotal = 0
		}

		return "", nil, io.EOF
	}

	// Read key
	var key string
	key = func() string {
		if sd.ctx.IsStringTable() {
			return sd.ctx.Table[sd.buff.ReadInt()]
		} else {
			return sd.buff.ReadString()
		}
	}()

	// Read value
	var value *Namespace
	if sd.buff.ReadUInt8() != uint8(0) {
		tempVal := &Namespace{}
		sd.buff.ReadInt() // compatibility
		err := tempVal.UnmarshalBinaryWithContext(sd.ctx)
		if err != nil {
			return "", nil, err
		}
		value = tempVal
	}

	sd.namespacesRead++
	return key, value, nil
}

// NextResourceQuotas reads and returns the next ResourceQuotas entry from the stream.
// Returns (key, value, nil) on success, or (zero, zero, io.EOF) when no more entries.
func (sd *StreamingKubeModelSetDecoder) NextResourceQuotas() (string, *ResourceQuota, error) {
	if !sd.initialized {
		return "", nil, fmt.Errorf("decoder not initialized")
	}

	if sd.currentSection != "resourceQuotas" {
		return "", nil, fmt.Errorf("not in resourceQuotas section")
	}

	if sd.resourceQuotasRead >= sd.resourceQuotasTotal {
		return "", nil, io.EOF
	}

	// Read key
	var key string
	key = func() string {
		if sd.ctx.IsStringTable() {
			return sd.ctx.Table[sd.buff.ReadInt()]
		} else {
			return sd.buff.ReadString()
		}
	}()

	// Read value
	var value *ResourceQuota
	if sd.buff.ReadUInt8() != uint8(0) {
		tempVal := &ResourceQuota{}
		sd.buff.ReadInt() // compatibility
		err := tempVal.UnmarshalBinaryWithContext(sd.ctx)
		if err != nil {
			return "", nil, err
		}
		value = tempVal
	}

	sd.resourceQuotasRead++
	return key, value, nil
}

// Stats returns statistics about the streaming decoder state.
func (sd *StreamingKubeModelSetDecoder) Stats() map[string]interface{} {
	return map[string]interface{}{
		"initialized":         sd.initialized,
		"version":             sd.version,
		"namespacesRead":      sd.namespacesRead,
		"namespacesTotal":     sd.namespacesTotal,
		"resourceQuotasRead":  sd.resourceQuotasRead,
		"resourceQuotasTotal": sd.resourceQuotasTotal,
		"currentSection":      sd.currentSection,
	}
}
