package kubemodel

import (
	"github.com/opencost/opencost/core/pkg/model/pb"
	kubepb "github.com/opencost/opencost/core/pkg/model/pb/kubemodel"
	"google.golang.org/protobuf/proto"
)

// ============================================================================
// Model Structure
// ============================================================================

// Model is a complete snapshot of a Kubernetes cluster at a specific time window.
//
// The Model contains all cluster resources organized into typed maps, with each
// resource keyed by its stable Kubernetes UID. This design enables:
//   - Fast lookups by UID
//   - Automatic deduplication (same UID = same resource)
//   - Efficient merging of models from different sources
//
// Resource Organization:
//
//	Metadata:
//	  - Window:  Timeframe and resolution for this snapshot
//	  - Cluster: Cluster identity (ID, name, provider, account)
//
//	Infrastructure (provisioned resources):
//	  - Nodes:      Worker nodes in the cluster
//	  - GPUDevices: GPU hardware attached to nodes
//	  - Volumes:    Persistent volumes (PVs)
//
//	Workloads (allocated resources):
//	  - Namespaces:  Logical groupings for resources
//	  - Controllers: Deployments, StatefulSets, DaemonSets, Jobs
//	  - Pods:        Running pod instances
//	  - Containers:  Containers within pods
//	  - PVCs:        Persistent volume claims
//
//	Networking:
//	  - Services: Kubernetes services (LoadBalancer, ClusterIP, etc.)
//
// Key Indexing:
// All maps use Kubernetes UIDs as keys. UIDs are:
//   - Unique across the cluster
//   - Stable for the lifetime of the resource
//   - Automatically generated by Kubernetes
//
// For resources without UIDs (or when UIDs are unavailable), synthetic keys
// are generated in the format "cluster/namespace/name".
type Model struct {
	// Metadata: timeframe and cluster identity
	Window  *pb.Window      // Time window and resolution for this snapshot
	Cluster *kubepb.Cluster // Cluster metadata (ID, name, provider, account)

	// Infrastructure: provisioned compute and storage resources
	Nodes      map[string]*kubepb.Node      // Keyed by node UID or name
	GPUDevices map[string]*kubepb.GPUDevice // Keyed by GPU device UUID
	Volumes    map[string]*kubepb.Volume    // Keyed by PV UID

	// Workloads: allocated resources and their organization
	Namespaces  map[string]*kubepb.Namespace              // Keyed by namespace UID
	Controllers map[string]*kubepb.Controller             // Keyed by controller UID
	Pods        map[string]*kubepb.Pod                    // Keyed by pod UID
	Containers  map[string]*kubepb.Container              // Keyed by container ID
	PVCs        map[string]*kubepb.PersistentVolumeClaim  // Keyed by PVC UID

	// Networking: service discovery and load balancing
	Services map[string]*kubepb.Service // Keyed by service UID
}

// ============================================================================
// Model Construction
// ============================================================================

// NewModel creates and returns an empty Model with all resource maps pre-initialized.
//
// All maps are created with zero capacity but non-nil values, which:
//   - Allows immediate insertion without nil checks
//   - Prevents nil pointer dereferences during iteration
//   - Provides consistent behavior across all resource types
//
// The Model is ready to be populated by hydrators or manual resource insertion.
// Window and Cluster metadata should be set separately after construction.
func NewModel() *Model {
	return &Model{
		Nodes:       make(map[string]*kubepb.Node),
		GPUDevices:  make(map[string]*kubepb.GPUDevice),
		Volumes:     make(map[string]*kubepb.Volume),
		PVCs:        make(map[string]*kubepb.PersistentVolumeClaim),
		Controllers: make(map[string]*kubepb.Controller),
		Namespaces:  make(map[string]*kubepb.Namespace),
		Pods:        make(map[string]*kubepb.Pod),
		Containers:  make(map[string]*kubepb.Container),
		Services:    make(map[string]*kubepb.Service),
	}
}

// ============================================================================
// Model Operations
// ============================================================================

// Clone creates a deep copy of the Model, allowing safe concurrent mutations.
//
// Deep copying is essential because protobuf messages contain pointer fields and
// nested structures. Without deep copying, modifications to the clone would affect
// the original Model through shared references.
//
// The function uses proto.Clone() to ensure all nested structures are properly
// copied, including:
//   - Maps within protobuf messages (labels, annotations)
//   - Nested message fields
//   - Repeated fields (arrays/slices)
//
// Use cases:
//   - Concurrent processing: Multiple goroutines can work on independent copies
//   - Safe mutations: Modify a copy without affecting the original
//   - Snapshotting: Preserve a point-in-time view of the model
//
// Returns nil if the input model is nil.
func (m *Model) Clone() *Model {
	if m == nil {
		return nil
	}

	cloned := NewModel()

	// Clone metadata
	if m.Window != nil {
		cloned.Window = proto.Clone(m.Window).(*pb.Window)
	}
	if m.Cluster != nil {
		cloned.Cluster = proto.Clone(m.Cluster).(*kubepb.Cluster)
	}

	// Clone infrastructure resources
	for id, node := range m.Nodes {
		cloned.Nodes[id] = proto.Clone(node).(*kubepb.Node)
	}
	for id, gpu := range m.GPUDevices {
		cloned.GPUDevices[id] = proto.Clone(gpu).(*kubepb.GPUDevice)
	}
	for id, volume := range m.Volumes {
		cloned.Volumes[id] = proto.Clone(volume).(*kubepb.Volume)
	}

	// Clone workload resources
	for id, pvc := range m.PVCs {
		cloned.PVCs[id] = proto.Clone(pvc).(*kubepb.PersistentVolumeClaim)
	}
	for id, controller := range m.Controllers {
		cloned.Controllers[id] = proto.Clone(controller).(*kubepb.Controller)
	}
	for id, ns := range m.Namespaces {
		cloned.Namespaces[id] = proto.Clone(ns).(*kubepb.Namespace)
	}
	for id, pod := range m.Pods {
		cloned.Pods[id] = proto.Clone(pod).(*kubepb.Pod)
	}
	for id, container := range m.Containers {
		cloned.Containers[id] = proto.Clone(container).(*kubepb.Container)
	}

	// Clone networking resources
	for id, svc := range m.Services {
		cloned.Services[id] = proto.Clone(svc).(*kubepb.Service)
	}

	return cloned
}

// Merge combines resources from another Model into the receiver.
//
// The merge operation copies all resources from the source model into the receiver,
// with the following semantics:
//   - Resources are identified by their UID keys
//   - Existing resources with the same UID are overwritten with the new version
//   - New resources are added to the receiver
//   - Resources only in the receiver are left unchanged
//
// Deep copying is used during the merge to prevent shared references between
// the two models. This ensures that subsequent mutations to either model don't
// affect the other.
//
// Use cases:
//   - Combining models from different hydrators (e.g., labels + metrics)
//   - Merging partial updates into a complete model
//   - Building composite models from multiple data sources
//   - Updating a model with incremental changes
//
// Merge semantics:
//   - Window: Replaced with the source model's window
//   - Cluster: Replaced with the source model's cluster metadata
//   - Resources: Merged by UID (source wins on conflicts)
//
// The function safely handles nil receivers or sources by returning early.
func (m *Model) Merge(other *Model) {
	if m == nil || other == nil {
		return
	}

	// Merge metadata (source overwrites receiver)
	if other.Window != nil {
		m.Window = proto.Clone(other.Window).(*pb.Window)
	}
	if other.Cluster != nil {
		m.Cluster = proto.Clone(other.Cluster).(*kubepb.Cluster)
	}

	// Merge infrastructure resources
	for id, node := range other.Nodes {
		m.Nodes[id] = proto.Clone(node).(*kubepb.Node)
	}
	for id, gpu := range other.GPUDevices {
		m.GPUDevices[id] = proto.Clone(gpu).(*kubepb.GPUDevice)
	}
	for id, volume := range other.Volumes {
		m.Volumes[id] = proto.Clone(volume).(*kubepb.Volume)
	}

	// Merge workload resources
	for id, pvc := range other.PVCs {
		m.PVCs[id] = proto.Clone(pvc).(*kubepb.PersistentVolumeClaim)
	}
	for id, controller := range other.Controllers {
		m.Controllers[id] = proto.Clone(controller).(*kubepb.Controller)
	}
	for id, ns := range other.Namespaces {
		m.Namespaces[id] = proto.Clone(ns).(*kubepb.Namespace)
	}
	for id, pod := range other.Pods {
		m.Pods[id] = proto.Clone(pod).(*kubepb.Pod)
	}
	for id, container := range other.Containers {
		m.Containers[id] = proto.Clone(container).(*kubepb.Container)
	}

	// Merge networking resources
	for id, svc := range other.Services {
		m.Services[id] = proto.Clone(svc).(*kubepb.Service)
	}
}
