syntax = "proto3";

import "google/protobuf/timestamp.proto";

package opencost.dm2;
option go_package = "github.com/opencost/opencost/pkg/agent/protos;protos";

// Node represents a Kubernetes worker node (provisioned resource)
message Node {
  // Identification
  string ID = 1;
  string ProviderResourceID = 2;

  // Properties
  string Name = 3;
  string InstanceType = 4;
  bool Preemptible = 5;
  map<string, string> Labels = 6;
  map<string, string> Annotations = 7;

  // Window
  google.protobuf.Timestamp WindowStart = 8;
  google.protobuf.Timestamp WindowEnd = 9;

  // Data (timing, resource, default pricing)
  google.protobuf.Timestamp Start = 10;
  google.protobuf.Timestamp End = 11;
  float CPUCores = 12;
  float RAMBytes = 13;
  float GPUs = 14;
  float DiskBytes = 15;
  float PricePerCPUHour = 16;
  float PricePerRAMByteHour = 17;
  float PricePerGPUHour = 18;
  float PricePerDiskByte = 19;
  float CPUOverheadFraction = 20;
  float RAMOverheadFraction = 21;
}