syntax = "proto3";

import "google/protobuf/timestamp.proto";

package opencost.dm2;
option go_package = "github.com/opencost/opencost/pkg/agent/protos;protos";

// Pod represents a Kubernetes pod (allocated resource grouping)
message Pod {
  // Identification
  string ID = 1;
  string NodeID = 2;
  string NamespaceID = 3;

  // Properties
  string Name = 4;
  string Phase = 5;
  string QOSClass = 6;
  string RestartPolicy = 7;
  string PriorityClass = 8;
  int64 CreatedAt = 9;
  int64 StartedAt = 10;
  map<string, string> Labels = 11;
  map<string, string> Annotations = 12;

  // Window
  google.protobuf.Timestamp WindowStart = 13;
  google.protobuf.Timestamp WindowEnd = 14;

  // Data (timing, resource, default pricing)
  google.protobuf.Timestamp Start = 15;
  google.protobuf.Timestamp End = 16;
}

// Container represents a container within a pod (allocated resource)
message Container {
  // Identification
  string ID = 1;
  string PodID = 2;

  // Properties
  string Name = 3;
  string Image = 4;
  string State = 5;
  int32 RestartCount = 6;
  int64 CreatedAt = 7;
  int64 StartedAt = 8;

  // Window
  google.protobuf.Timestamp WindowStart = 9;
  google.protobuf.Timestamp WindowEnd = 10;

  // Data (timing, resource, default pricing)
  google.protobuf.Timestamp Start = 11;
  google.protobuf.Timestamp End = 12;
  float ResourceUtilization = 13;
}