// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.3
// source: pkg/agent/protos/infrastructure.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cluster represents the top-level container following normalized approach
type Cluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Properties
	Provider Provider `protobuf:"varint,2,opt,name=Provider,proto3,enum=opencost.dm2.Provider" json:"Provider,omitempty"`
	Account  string   `protobuf:"bytes,3,opt,name=Account,proto3" json:"Account,omitempty"`
	Project  string   `protobuf:"bytes,4,opt,name=Project,proto3" json:"Project,omitempty"`
	// Window
	WindowStart *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=WindowStart,proto3" json:"WindowStart,omitempty"`
	WindowEnd   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=WindowEnd,proto3" json:"WindowEnd,omitempty"`
	// Data
	ManagementFeePerHour float32  `protobuf:"fixed32,7,opt,name=ManagementFeePerHour,proto3" json:"ManagementFeePerHour,omitempty"`
	Errors               []string `protobuf:"bytes,8,rep,name=Errors,proto3" json:"Errors,omitempty"`
	Warnings             []string `protobuf:"bytes,9,rep,name=Warnings,proto3" json:"Warnings,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_pkg_agent_protos_infrastructure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protos_infrastructure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protos_infrastructure_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Cluster) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_AWS
}

func (x *Cluster) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Cluster) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Cluster) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *Cluster) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *Cluster) GetManagementFeePerHour() float32 {
	if x != nil {
		return x.ManagementFeePerHour
	}
	return 0
}

func (x *Cluster) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *Cluster) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_pkg_agent_protos_infrastructure_proto protoreflect.FileDescriptor

const file_pkg_agent_protos_infrastructure_proto_rawDesc = "" +
	"\n" +
	"%pkg/agent/protos/infrastructure.proto\x12\fopencost.dm2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dpkg/agent/protos/common.proto\"\xe1\x02\n" +
	"\aCluster\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x122\n" +
	"\bProvider\x18\x02 \x01(\x0e2\x16.opencost.dm2.ProviderR\bProvider\x12\x18\n" +
	"\aAccount\x18\x03 \x01(\tR\aAccount\x12\x18\n" +
	"\aProject\x18\x04 \x01(\tR\aProject\x12<\n" +
	"\vWindowStart\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vWindowStart\x128\n" +
	"\tWindowEnd\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tWindowEnd\x122\n" +
	"\x14ManagementFeePerHour\x18\a \x01(\x02R\x14ManagementFeePerHour\x12\x16\n" +
	"\x06Errors\x18\b \x03(\tR\x06Errors\x12\x1a\n" +
	"\bWarnings\x18\t \x03(\tR\bWarningsB6Z4github.com/opencost/opencost/pkg/agent/protos;protosb\x06proto3"

var (
	file_pkg_agent_protos_infrastructure_proto_rawDescOnce sync.Once
	file_pkg_agent_protos_infrastructure_proto_rawDescData []byte
)

func file_pkg_agent_protos_infrastructure_proto_rawDescGZIP() []byte {
	file_pkg_agent_protos_infrastructure_proto_rawDescOnce.Do(func() {
		file_pkg_agent_protos_infrastructure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_protos_infrastructure_proto_rawDesc), len(file_pkg_agent_protos_infrastructure_proto_rawDesc)))
	})
	return file_pkg_agent_protos_infrastructure_proto_rawDescData
}

var file_pkg_agent_protos_infrastructure_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_agent_protos_infrastructure_proto_goTypes = []any{
	(*Cluster)(nil),               // 0: opencost.dm2.Cluster
	(Provider)(0),                 // 1: opencost.dm2.Provider
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_agent_protos_infrastructure_proto_depIdxs = []int32{
	1, // 0: opencost.dm2.Cluster.Provider:type_name -> opencost.dm2.Provider
	2, // 1: opencost.dm2.Cluster.WindowStart:type_name -> google.protobuf.Timestamp
	2, // 2: opencost.dm2.Cluster.WindowEnd:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_agent_protos_infrastructure_proto_init() }
func file_pkg_agent_protos_infrastructure_proto_init() {
	if File_pkg_agent_protos_infrastructure_proto != nil {
		return
	}
	file_pkg_agent_protos_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_protos_infrastructure_proto_rawDesc), len(file_pkg_agent_protos_infrastructure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_agent_protos_infrastructure_proto_goTypes,
		DependencyIndexes: file_pkg_agent_protos_infrastructure_proto_depIdxs,
		MessageInfos:      file_pkg_agent_protos_infrastructure_proto_msgTypes,
	}.Build()
	File_pkg_agent_protos_infrastructure_proto = out.File
	file_pkg_agent_protos_infrastructure_proto_goTypes = nil
	file_pkg_agent_protos_infrastructure_proto_depIdxs = nil
}
