// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.3
// source: pods.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pod represents a Kubernetes pod (allocated resource grouping)
type Pod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NodeID      string `protobuf:"bytes,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	NamespaceID string `protobuf:"bytes,3,opt,name=NamespaceID,proto3" json:"NamespaceID,omitempty"`
	// Properties
	Name        string            `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Labels      map[string]string `protobuf:"bytes,5,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string `protobuf:"bytes,6,rep,name=Annotations,proto3" json:"Annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource lifecycle (only when different from cluster window)
	Lifetime *ResourceLifetime `protobuf:"bytes,7,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	// Cost allocation data (optional - only populated for cost-enabled exports)
	Cost *AllocationCost `protobuf:"bytes,8,opt,name=cost,proto3" json:"cost,omitempty"`
	// Cost attribution for this pod
	CostAttribution *CostAttribution `protobuf:"bytes,9,opt,name=cost_attribution,json=costAttribution,proto3" json:"cost_attribution,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_pods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_pods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_pods_proto_rawDescGZIP(), []int{0}
}

func (x *Pod) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Pod) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Pod) GetNamespaceID() string {
	if x != nil {
		return x.NamespaceID
	}
	return ""
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Pod) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Pod) GetLifetime() *ResourceLifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *Pod) GetCost() *AllocationCost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Pod) GetCostAttribution() *CostAttribution {
	if x != nil {
		return x.CostAttribution
	}
	return nil
}

// Container represents a container within a pod (allocated resource)
type Container struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	ID    string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` //{pod-uid}/{container-name}
	PodID string `protobuf:"bytes,2,opt,name=PodID,proto3" json:"PodID,omitempty"`
	// Properties
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	// Resource lifecycle (only when different from cluster window)
	Lifetime *ResourceLifetime `protobuf:"bytes,4,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	// Cost allocation data (optional - only populated for cost-enabled exports)
	Cost *AllocationCost `protobuf:"bytes,5,opt,name=cost,proto3" json:"cost,omitempty"`
	// Cost attribution for this container
	CostAttribution *CostAttribution `protobuf:"bytes,6,opt,name=cost_attribution,json=costAttribution,proto3" json:"cost_attribution,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_pods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_pods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_pods_proto_rawDescGZIP(), []int{1}
}

func (x *Container) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Container) GetPodID() string {
	if x != nil {
		return x.PodID
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetLifetime() *ResourceLifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *Container) GetCost() *AllocationCost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Container) GetCostAttribution() *CostAttribution {
	if x != nil {
		return x.CostAttribution
	}
	return nil
}

var File_pods_proto protoreflect.FileDescriptor

const file_pods_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pods.proto\x12\x05agent\x1a\fcommon.proto\x1a\vcosts.proto\"\xf0\x03\n" +
	"\x03Pod\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06NodeID\x18\x02 \x01(\tR\x06NodeID\x12 \n" +
	"\vNamespaceID\x18\x03 \x01(\tR\vNamespaceID\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12.\n" +
	"\x06Labels\x18\x05 \x03(\v2\x16.agent.Pod.LabelsEntryR\x06Labels\x12=\n" +
	"\vAnnotations\x18\x06 \x03(\v2\x1b.agent.Pod.AnnotationsEntryR\vAnnotations\x123\n" +
	"\blifetime\x18\a \x01(\v2\x17.agent.ResourceLifetimeR\blifetime\x12)\n" +
	"\x04cost\x18\b \x01(\v2\x15.agent.AllocationCostR\x04cost\x12A\n" +
	"\x10cost_attribution\x18\t \x01(\v2\x16.agent.CostAttributionR\x0fcostAttribution\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05PodID\x18\x02 \x01(\tR\x05PodID\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x123\n" +
	"\blifetime\x18\x04 \x01(\v2\x17.agent.ResourceLifetimeR\blifetime\x12)\n" +
	"\x04cost\x18\x05 \x01(\v2\x15.agent.AllocationCostR\x04cost\x12A\n" +
	"\x10cost_attribution\x18\x06 \x01(\v2\x16.agent.CostAttributionR\x0fcostAttributionB4Z2github.com/opencost/opencost/pkg/agent/model/pb;pbb\x06proto3"

var (
	file_pods_proto_rawDescOnce sync.Once
	file_pods_proto_rawDescData []byte
)

func file_pods_proto_rawDescGZIP() []byte {
	file_pods_proto_rawDescOnce.Do(func() {
		file_pods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pods_proto_rawDesc), len(file_pods_proto_rawDesc)))
	})
	return file_pods_proto_rawDescData
}

var file_pods_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pods_proto_goTypes = []any{
	(*Pod)(nil),              // 0: agent.Pod
	(*Container)(nil),        // 1: agent.Container
	nil,                      // 2: agent.Pod.LabelsEntry
	nil,                      // 3: agent.Pod.AnnotationsEntry
	(*ResourceLifetime)(nil), // 4: agent.ResourceLifetime
	(*AllocationCost)(nil),   // 5: agent.AllocationCost
	(*CostAttribution)(nil),  // 6: agent.CostAttribution
}
var file_pods_proto_depIdxs = []int32{
	2, // 0: agent.Pod.Labels:type_name -> agent.Pod.LabelsEntry
	3, // 1: agent.Pod.Annotations:type_name -> agent.Pod.AnnotationsEntry
	4, // 2: agent.Pod.lifetime:type_name -> agent.ResourceLifetime
	5, // 3: agent.Pod.cost:type_name -> agent.AllocationCost
	6, // 4: agent.Pod.cost_attribution:type_name -> agent.CostAttribution
	4, // 5: agent.Container.lifetime:type_name -> agent.ResourceLifetime
	5, // 6: agent.Container.cost:type_name -> agent.AllocationCost
	6, // 7: agent.Container.cost_attribution:type_name -> agent.CostAttribution
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pods_proto_init() }
func file_pods_proto_init() {
	if File_pods_proto != nil {
		return
	}
	file_common_proto_init()
	file_costs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pods_proto_rawDesc), len(file_pods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pods_proto_goTypes,
		DependencyIndexes: file_pods_proto_depIdxs,
		MessageInfos:      file_pods_proto_msgTypes,
	}.Build()
	File_pods_proto = out.File
	file_pods_proto_goTypes = nil
	file_pods_proto_depIdxs = nil
}
