// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.3
// source: pkg/agent/protos/sources.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataSourceMetadata tracks how data was collected (for Source interface)
type DataSourceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary data source type
	PrimarySource DataSourceType `protobuf:"varint,1,opt,name=primary_source,json=primarySource,proto3,enum=opencost.dm2.DataSourceType" json:"primary_source,omitempty"`
	// Fallback sources used if primary failed
	FallbackSources []DataSourceType `protobuf:"varint,2,rep,packed,name=fallback_sources,json=fallbackSources,proto3,enum=opencost.dm2.DataSourceType" json:"fallback_sources,omitempty"`
	// Prometheus query metadata if applicable
	PrometheusInfo *PrometheusSourceInfo `protobuf:"bytes,3,opt,name=prometheus_info,json=prometheusInfo,proto3" json:"prometheus_info,omitempty"`
	// Kubernetes API metadata if applicable
	K8SApiInfo *KubernetesAPISourceInfo `protobuf:"bytes,4,opt,name=k8s_api_info,json=k8sApiInfo,proto3" json:"k8s_api_info,omitempty"`
	// Data collection timestamp
	CollectedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	// Collection duration in milliseconds
	CollectionDurationMs int64 `protobuf:"varint,6,opt,name=collection_duration_ms,json=collectionDurationMs,proto3" json:"collection_duration_ms,omitempty"`
	// Collection success/failure status
	CollectionSuccess bool `protobuf:"varint,7,opt,name=collection_success,json=collectionSuccess,proto3" json:"collection_success,omitempty"`
	// Collection errors if any
	CollectionErrors []string `protobuf:"bytes,8,rep,name=collection_errors,json=collectionErrors,proto3" json:"collection_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DataSourceMetadata) Reset() {
	*x = DataSourceMetadata{}
	mi := &file_pkg_agent_protos_sources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceMetadata) ProtoMessage() {}

func (x *DataSourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protos_sources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceMetadata.ProtoReflect.Descriptor instead.
func (*DataSourceMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protos_sources_proto_rawDescGZIP(), []int{0}
}

func (x *DataSourceMetadata) GetPrimarySource() DataSourceType {
	if x != nil {
		return x.PrimarySource
	}
	return DataSourceType_DATA_SOURCE_UNSPECIFIED
}

func (x *DataSourceMetadata) GetFallbackSources() []DataSourceType {
	if x != nil {
		return x.FallbackSources
	}
	return nil
}

func (x *DataSourceMetadata) GetPrometheusInfo() *PrometheusSourceInfo {
	if x != nil {
		return x.PrometheusInfo
	}
	return nil
}

func (x *DataSourceMetadata) GetK8SApiInfo() *KubernetesAPISourceInfo {
	if x != nil {
		return x.K8SApiInfo
	}
	return nil
}

func (x *DataSourceMetadata) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *DataSourceMetadata) GetCollectionDurationMs() int64 {
	if x != nil {
		return x.CollectionDurationMs
	}
	return 0
}

func (x *DataSourceMetadata) GetCollectionSuccess() bool {
	if x != nil {
		return x.CollectionSuccess
	}
	return false
}

func (x *DataSourceMetadata) GetCollectionErrors() []string {
	if x != nil {
		return x.CollectionErrors
	}
	return nil
}

// Prometheus-specific source information
type PrometheusSourceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prometheus server URL used
	PrometheusUrl string `protobuf:"bytes,1,opt,name=prometheus_url,json=prometheusUrl,proto3" json:"prometheus_url,omitempty"`
	// Query used to collect this data
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Query execution time
	QueryDurationMs int64 `protobuf:"varint,3,opt,name=query_duration_ms,json=queryDurationMs,proto3" json:"query_duration_ms,omitempty"`
	// Number of samples returned
	SampleCount int32 `protobuf:"varint,4,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	// Prometheus scrape interval used
	ScrapeIntervalSeconds int32 `protobuf:"varint,5,opt,name=scrape_interval_seconds,json=scrapeIntervalSeconds,proto3" json:"scrape_interval_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PrometheusSourceInfo) Reset() {
	*x = PrometheusSourceInfo{}
	mi := &file_pkg_agent_protos_sources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrometheusSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrometheusSourceInfo) ProtoMessage() {}

func (x *PrometheusSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protos_sources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrometheusSourceInfo.ProtoReflect.Descriptor instead.
func (*PrometheusSourceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protos_sources_proto_rawDescGZIP(), []int{1}
}

func (x *PrometheusSourceInfo) GetPrometheusUrl() string {
	if x != nil {
		return x.PrometheusUrl
	}
	return ""
}

func (x *PrometheusSourceInfo) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PrometheusSourceInfo) GetQueryDurationMs() int64 {
	if x != nil {
		return x.QueryDurationMs
	}
	return 0
}

func (x *PrometheusSourceInfo) GetSampleCount() int32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *PrometheusSourceInfo) GetScrapeIntervalSeconds() int32 {
	if x != nil {
		return x.ScrapeIntervalSeconds
	}
	return 0
}

// Kubernetes API-specific source information
type KubernetesAPISourceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// K8s API server endpoint
	ApiServer string `protobuf:"bytes,1,opt,name=api_server,json=apiServer,proto3" json:"api_server,omitempty"`
	// Resource types queried
	ResourceTypes []string `protobuf:"bytes,2,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	// Namespace scope (empty means cluster-wide)
	NamespaceScope string `protobuf:"bytes,3,opt,name=namespace_scope,json=namespaceScope,proto3" json:"namespace_scope,omitempty"`
	// API version used
	ApiVersion string `protobuf:"bytes,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Field selectors used
	FieldSelectors []string `protobuf:"bytes,5,rep,name=field_selectors,json=fieldSelectors,proto3" json:"field_selectors,omitempty"`
	// Label selectors used
	LabelSelectors []string `protobuf:"bytes,6,rep,name=label_selectors,json=labelSelectors,proto3" json:"label_selectors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KubernetesAPISourceInfo) Reset() {
	*x = KubernetesAPISourceInfo{}
	mi := &file_pkg_agent_protos_sources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesAPISourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesAPISourceInfo) ProtoMessage() {}

func (x *KubernetesAPISourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protos_sources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesAPISourceInfo.ProtoReflect.Descriptor instead.
func (*KubernetesAPISourceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protos_sources_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesAPISourceInfo) GetApiServer() string {
	if x != nil {
		return x.ApiServer
	}
	return ""
}

func (x *KubernetesAPISourceInfo) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *KubernetesAPISourceInfo) GetNamespaceScope() string {
	if x != nil {
		return x.NamespaceScope
	}
	return ""
}

func (x *KubernetesAPISourceInfo) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *KubernetesAPISourceInfo) GetFieldSelectors() []string {
	if x != nil {
		return x.FieldSelectors
	}
	return nil
}

func (x *KubernetesAPISourceInfo) GetLabelSelectors() []string {
	if x != nil {
		return x.LabelSelectors
	}
	return nil
}

var File_pkg_agent_protos_sources_proto protoreflect.FileDescriptor

const file_pkg_agent_protos_sources_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/agent/protos/sources.proto\x12\fopencost.dm2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dpkg/agent/protos/common.proto\"\x89\x04\n" +
	"\x12DataSourceMetadata\x12C\n" +
	"\x0eprimary_source\x18\x01 \x01(\x0e2\x1c.opencost.dm2.DataSourceTypeR\rprimarySource\x12G\n" +
	"\x10fallback_sources\x18\x02 \x03(\x0e2\x1c.opencost.dm2.DataSourceTypeR\x0ffallbackSources\x12K\n" +
	"\x0fprometheus_info\x18\x03 \x01(\v2\".opencost.dm2.PrometheusSourceInfoR\x0eprometheusInfo\x12G\n" +
	"\fk8s_api_info\x18\x04 \x01(\v2%.opencost.dm2.KubernetesAPISourceInfoR\n" +
	"k8sApiInfo\x12=\n" +
	"\fcollected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x124\n" +
	"\x16collection_duration_ms\x18\x06 \x01(\x03R\x14collectionDurationMs\x12-\n" +
	"\x12collection_success\x18\a \x01(\bR\x11collectionSuccess\x12+\n" +
	"\x11collection_errors\x18\b \x03(\tR\x10collectionErrors\"\xda\x01\n" +
	"\x14PrometheusSourceInfo\x12%\n" +
	"\x0eprometheus_url\x18\x01 \x01(\tR\rprometheusUrl\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12*\n" +
	"\x11query_duration_ms\x18\x03 \x01(\x03R\x0fqueryDurationMs\x12!\n" +
	"\fsample_count\x18\x04 \x01(\x05R\vsampleCount\x126\n" +
	"\x17scrape_interval_seconds\x18\x05 \x01(\x05R\x15scrapeIntervalSeconds\"\xfb\x01\n" +
	"\x17KubernetesAPISourceInfo\x12\x1d\n" +
	"\n" +
	"api_server\x18\x01 \x01(\tR\tapiServer\x12%\n" +
	"\x0eresource_types\x18\x02 \x03(\tR\rresourceTypes\x12'\n" +
	"\x0fnamespace_scope\x18\x03 \x01(\tR\x0enamespaceScope\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\tR\n" +
	"apiVersion\x12'\n" +
	"\x0ffield_selectors\x18\x05 \x03(\tR\x0efieldSelectors\x12'\n" +
	"\x0flabel_selectors\x18\x06 \x03(\tR\x0elabelSelectorsB6Z4github.com/opencost/opencost/pkg/agent/protos;protosb\x06proto3"

var (
	file_pkg_agent_protos_sources_proto_rawDescOnce sync.Once
	file_pkg_agent_protos_sources_proto_rawDescData []byte
)

func file_pkg_agent_protos_sources_proto_rawDescGZIP() []byte {
	file_pkg_agent_protos_sources_proto_rawDescOnce.Do(func() {
		file_pkg_agent_protos_sources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_protos_sources_proto_rawDesc), len(file_pkg_agent_protos_sources_proto_rawDesc)))
	})
	return file_pkg_agent_protos_sources_proto_rawDescData
}

var file_pkg_agent_protos_sources_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_agent_protos_sources_proto_goTypes = []any{
	(*DataSourceMetadata)(nil),      // 0: opencost.dm2.DataSourceMetadata
	(*PrometheusSourceInfo)(nil),    // 1: opencost.dm2.PrometheusSourceInfo
	(*KubernetesAPISourceInfo)(nil), // 2: opencost.dm2.KubernetesAPISourceInfo
	(DataSourceType)(0),             // 3: opencost.dm2.DataSourceType
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_pkg_agent_protos_sources_proto_depIdxs = []int32{
	3, // 0: opencost.dm2.DataSourceMetadata.primary_source:type_name -> opencost.dm2.DataSourceType
	3, // 1: opencost.dm2.DataSourceMetadata.fallback_sources:type_name -> opencost.dm2.DataSourceType
	1, // 2: opencost.dm2.DataSourceMetadata.prometheus_info:type_name -> opencost.dm2.PrometheusSourceInfo
	2, // 3: opencost.dm2.DataSourceMetadata.k8s_api_info:type_name -> opencost.dm2.KubernetesAPISourceInfo
	4, // 4: opencost.dm2.DataSourceMetadata.collected_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_agent_protos_sources_proto_init() }
func file_pkg_agent_protos_sources_proto_init() {
	if File_pkg_agent_protos_sources_proto != nil {
		return
	}
	file_pkg_agent_protos_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_protos_sources_proto_rawDesc), len(file_pkg_agent_protos_sources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_agent_protos_sources_proto_goTypes,
		DependencyIndexes: file_pkg_agent_protos_sources_proto_depIdxs,
		MessageInfos:      file_pkg_agent_protos_sources_proto_msgTypes,
	}.Build()
	File_pkg_agent_protos_sources_proto = out.File
	file_pkg_agent_protos_sources_proto_goTypes = nil
	file_pkg_agent_protos_sources_proto_depIdxs = nil
}
