// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.3
// source: pkg/agent/protos/workloads.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Namespace represents a Kubernetes namespace (allocated resource grouping)
type Namespace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identification
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Properties
	Name        string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatedAt   int64             `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Labels      map[string]string `protobuf:"bytes,4,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string `protobuf:"bytes,5,rep,name=Annotations,proto3" json:"Annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Window
	WindowStart *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=WindowStart,proto3" json:"WindowStart,omitempty"`
	WindowEnd   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=WindowEnd,proto3" json:"WindowEnd,omitempty"`
	// Data (timing, resource, default pricing)
	Start         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=Start,proto3" json:"Start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=End,proto3" json:"End,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_pkg_agent_protos_workloads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protos_workloads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protos_workloads_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Namespace) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Namespace) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Namespace) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *Namespace) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *Namespace) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Namespace) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

var File_pkg_agent_protos_workloads_proto protoreflect.FileDescriptor

const file_pkg_agent_protos_workloads_proto_rawDesc = "" +
	"\n" +
	" pkg/agent/protos/workloads.proto\x12\fopencost.dm2\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x04\n" +
	"\tNamespace\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1c\n" +
	"\tCreatedAt\x18\x03 \x01(\x03R\tCreatedAt\x12;\n" +
	"\x06Labels\x18\x04 \x03(\v2#.opencost.dm2.Namespace.LabelsEntryR\x06Labels\x12J\n" +
	"\vAnnotations\x18\x05 \x03(\v2(.opencost.dm2.Namespace.AnnotationsEntryR\vAnnotations\x12<\n" +
	"\vWindowStart\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vWindowStart\x128\n" +
	"\tWindowEnd\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tWindowEnd\x120\n" +
	"\x05Start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x05Start\x12,\n" +
	"\x03End\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x03End\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B6Z4github.com/opencost/opencost/pkg/agent/protos;protosb\x06proto3"

var (
	file_pkg_agent_protos_workloads_proto_rawDescOnce sync.Once
	file_pkg_agent_protos_workloads_proto_rawDescData []byte
)

func file_pkg_agent_protos_workloads_proto_rawDescGZIP() []byte {
	file_pkg_agent_protos_workloads_proto_rawDescOnce.Do(func() {
		file_pkg_agent_protos_workloads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_protos_workloads_proto_rawDesc), len(file_pkg_agent_protos_workloads_proto_rawDesc)))
	})
	return file_pkg_agent_protos_workloads_proto_rawDescData
}

var file_pkg_agent_protos_workloads_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_agent_protos_workloads_proto_goTypes = []any{
	(*Namespace)(nil),             // 0: opencost.dm2.Namespace
	nil,                           // 1: opencost.dm2.Namespace.LabelsEntry
	nil,                           // 2: opencost.dm2.Namespace.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_pkg_agent_protos_workloads_proto_depIdxs = []int32{
	1, // 0: opencost.dm2.Namespace.Labels:type_name -> opencost.dm2.Namespace.LabelsEntry
	2, // 1: opencost.dm2.Namespace.Annotations:type_name -> opencost.dm2.Namespace.AnnotationsEntry
	3, // 2: opencost.dm2.Namespace.WindowStart:type_name -> google.protobuf.Timestamp
	3, // 3: opencost.dm2.Namespace.WindowEnd:type_name -> google.protobuf.Timestamp
	3, // 4: opencost.dm2.Namespace.Start:type_name -> google.protobuf.Timestamp
	3, // 5: opencost.dm2.Namespace.End:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_agent_protos_workloads_proto_init() }
func file_pkg_agent_protos_workloads_proto_init() {
	if File_pkg_agent_protos_workloads_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_protos_workloads_proto_rawDesc), len(file_pkg_agent_protos_workloads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_agent_protos_workloads_proto_goTypes,
		DependencyIndexes: file_pkg_agent_protos_workloads_proto_depIdxs,
		MessageInfos:      file_pkg_agent_protos_workloads_proto_msgTypes,
	}.Build()
	File_pkg_agent_protos_workloads_proto = out.File
	file_pkg_agent_protos_workloads_proto_goTypes = nil
	file_pkg_agent_protos_workloads_proto_depIdxs = nil
}
