FROM nginx:alpine

COPY ./dist /var/www
COPY default.nginx.conf /etc/nginx/conf.d/
COPY nginx.conf /etc/nginx/
COPY ./docker-entrypoint.sh /usr/local/bin/

RUN adduser 1001 -g 1000 -D
RUN chown 1001:1000 -R /var/www
RUN chown 1001:1000 -R /etc/nginx

ENV BASE_URL=/model

USER 1001

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
