default:
    just --list

build-local:
    npm install
    npx parcel build src/index.html

build IMAGETAG: build-local
    # Building a multi-arch image with manifest-tool is not necessary for the UI
    # container because the base container is nginx:alpine which is already
    # multi-arch.

    docker buildx build \
        --rm \
        -f 'Dockerfile.cross' \
        -t {{IMAGETAG}} \
        .

build-push IMAGETAG: (build IMAGETAG)
    docker push {{IMAGETAG}}
