name: Build/Test

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

  merge_group:
    types: [checks_requested]

permissions: {}

jobs:
  validate-protobuf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          path: ./
      -
        name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 'stable'

      -
        name: Install protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: '32.1'
      -
        name: Install just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0
        with:
          just-version: '1.58.0'

      - name: install protobuf-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.9
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
          which protoc-gen-go-grpc
      -
        name: Validate
        run: |
          just validate-protobuf
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          path: ./

      -
        name: Install just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0
        with:
          just-version: '1.58.0'

      -
        name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 'stable'

      # Saves us from having to redownload all modules
      - name: Go Mod cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      -
        name: Test
        run: |
          just test

      -
        name: Build
        run: |
          just build-local
      - name: get-pr-info
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          echo $PR_NUM > pr_num.txt
          echo $GITHUB_BASE_REF > base.txt
          echo $GITHUB_HEAD_REF > head.txt

      - name: Upload code coverage
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: code-coverage
          path: |
           coverage.out
           pr_num.txt
           base.txt
           head.txt